### ISSUE TITLE
Zul'Farrak issues

### ISSUE THREAD

**Issue by grapedaddy** [Wall-core/Everlook-Bugtracker#10]
1.

Witch Doctor Zum'rah should summon 1 skeleton immediately when players fight him and then summon additional one every 15 seconds. This does not seem to happen currently. Here is video from TBC Classic: https://www.youtube.com/watch?v=5HlgM9pbzuc

**Comment by NickTyrer** [comment]
![Untitled](https://user-images.githubusercontent.com/22723839/175818792-f18ea0b7-5a8b-44fd-90d6-8ae09e57b00b.png)
Seems to work for me.

**Comment by Wall-core** [comment]
I need to test this one further
