### ISSUE TITLE
[Diremaul Tribute] Cho'Rush resets [Known vManGoS Bug]

### ISSUE THREAD

**Issue by Sh1NoX08** [Wall-core/Everlook-Bugtracker#101]
Known vmangos issue Diremaul: Cho'rush resets completely after pulling King Gordok in tribute when feign death is used. 

proof: https://imgur.com/Cv43HqV

**Comment by Wall-core** [comment]
Works fine on latest build

**Comment by vertria** [comment]
![WoWScrnShot_090422_143754](https://user-images.githubusercontent.com/88947171/188311626-c67ed93d-f842-411f-b1a2-af54bb37dcac.jpg)
still doesnot work

**Comment by vertria** [comment]
whisper raddix or neto they fixed this on DS
