### ISSUE TITLE
Sunken Temple issues

### ISSUE THREAD

**Issue by grapedaddy** [Wall-core/Everlook-Bugtracker#11]
1:

Zul'Lor (5716) one of the troll mini bosses is undead but not immune to bleeds (rend / deep wound). His fragility ability should hit the whole party, not just one player. Currently bleeds work on him and his fragility ability only hits one player.

2:

Avatar of Hakkar does not despawn if the only party member alive in his chamber is under MC. Once MC ends, combat drops and it's possible, if the mind-controlled character was a healer, for them to revive the party and they can go again without needing to use a second egg.

3:

Jammal'an the Prophet (5710) casts Mind Control and the transformation effect works but the character remains under player control and can continue attacking the boss. They should lose control.

**Comment by Wall-core** [comment]
For problem number 3, were you using GM mode or GM fly? If flying was enabled, it might have prevented loss of control

**Comment by grapedaddy** [comment]
> For problem number 3, were you using GM mode or GM fly? If flying was enabled, it might have prevented loss of control

This happened to a player without GM account.

**Comment by ratkosrb** [comment]
> > For problem number 3, were you using GM mode or GM fly? If flying was enabled, it might have prevented loss of control
> 
> This happened to a player without GM account.

Can't reproduce the bug. I have no control over my character when transformed. You can see all abilities are greyed out too.
![WoWScrnShot_070322_042724](https://user-images.githubusercontent.com/35845488/177020906-44de1705-6283-4eaf-9a48-138cb21a4cf7.jpg)

**Comment by ratkosrb** [comment]
> 1:
> 
> Zul'Lor (5716) one of the troll mini bosses is undead but not immune to bleeds (rend / deep wound). His fragility ability should hit the whole party, not just one player. Currently bleeds work on him and his fragility ability only hits one player.

He is not supposed to be immune to bleeds. I just tested it on Classic. You can see I've got both Rip and Rake on him. You should do some research before reporting things as bugs.

![WoWScrnShot_070322_050028](https://user-images.githubusercontent.com/35845488/177021590-b22aab6f-977d-454a-8354-38f113d35265.jpg)
