### ISSUE TITLE
hunter feign death bug , noncombat to combat !!! 

### ISSUE THREAD

**Issue by gigachadbro** [Wall-core/Everlook-Bugtracker#116]
hey after using feign death , even despite i dont attack and my pet dont attack , me as hunter i return to combat just 1 or 2 seconds after i use feign death 
it seem like its the pet of hunter that stays in combat , and it make hunter return to combat just after using the feign death

![image](https://user-images.githubusercontent.com/46192630/188272675-9dfdb763-4951-4c0a-b6c4-20b8c614bc8b.png)

**Comment by vertria** [comment]
its because of 5/8 t2 bonus aura
