### ISSUE TITLE
Oily Blackfins do not exist

### ISSUE THREAD

**Issue by P-l-i-n-y** [Wall-core/Everlook-Bugtracker#117]
I'm aware that fishing pools aren't added until 1.9, but I've been yet to successfully fish up a single oily blackmouth out of open waters. I've tried 5 common spots, Menethil Docks being where most my time has been spent... well over 200 fish now and not a single Oily Blackmouth.

hmm

**Comment by 123iqpl123** [comment]
2nding this. Droprate on other pservers and according to old comments on thottbot has been around 10%, I tested this out and had 0 Oily Blackmouths in Westfall, STV & Silverpine. 300 Fishing +75 Lure, 70 fish caught in Wetlands + STV and 50 in Silverpine. 

This is a gamebreaking bug, no faps and no easy fishing income for healers. Fix asap pls ty.

**Comment by Kantrul** [comment]
Can confirm, fishing for an hour in Darkshore and no Oily Blackmouth.

**Comment by Wall-core** [comment]
Oily blackmouth is working and drops. You're just fishing in the wrong subzone. The highest droprate is in "Wetlands", aka the zone "Wetlands" must be displayed above minimap. Menethil harbor, baradin bay, longshore, etc - these are all different zones. Go to this spot and fish:
![image](https://user-images.githubusercontent.com/90075138/189495401-f9f49974-dc11-499c-8f91-62e00e278172.png)
