### ISSUE TITLE
DME door event sometimes does not work

### ISSUE THREAD

**Issue by showabug** [Wall-core/Everlook-Bugtracker#118]
After talking to npc Ironbark the redeemed to start event in dme, he goes to suicide on door as usual, but door stays closed: 
https://imgur.com/OBbvmdm

**Comment by NickTyrer** [comment]
@Wall-core is this migration applied (https://github.com/vmangos/core/commit/b8ccb0397686e41d1c3ea2cb7214425cd998e7a4)? I attempted to fix this here?

**Comment by Wall-core** [comment]
> @Wall-core is this migration applied ([vmangos/core@b8ccb03](https://github.com/vmangos/core/commit/b8ccb0397686e41d1c3ea2cb7214425cd998e7a4))? I attempted to fix this here?

It's live on dev server but not on PTR, issue is resolved with your migration
