### ISSUE TITLE
troll racial berserking

### ISSUE THREAD

**Issue by ghost** [Wall-core/Everlook-Bugtracker#12]
the maximum haste bonus for caster classes should be 43% (10% × 30%)
currently it's only 30%

Greater Heal 3.0s cast time, <40% health
**everlook test realm** `3 ÷ 1.3 = 2.3`
**expected** `3 ÷ ( 1.3 × 1.1 ) = 3 ÷ 1.43 = 2.1`

> The Berserking Troll racial ability is behaving as expected and matches the reference client.
[WoW Classic "Not A Bug" List](https://us.forums.blizzard.com/en/wow/t/wow-classic-era-“not-a-bug”-list-updated-april-22-2021/175887)

reddit discussions
https://www.reddit.com/r/classicwow/comments/ce5q58/wow_classic_not_a_bug_list_wow_classic_beta_test/eu0ur0g/?utm_source=reddit&utm_medium=web2x&context=3
https://www.reddit.com/r/classicwow/comments/cew2qp/troll_racial_stacking_buffs/eu6c7ue/
https://www.reddit.com/r/classicwow/comments/cew2qp/troll_racial_stacking_buffs/eu5q0b9/
https://www.reddit.com/r/classicwow/comments/ce5q58/wow_classic_not_a_bug_list_wow_classic_beta_test/eu1x0aq/?utm_source=reddit&utm_medium=web2x&context=3
https://www.reddit.com/r/classicwow/comments/it9k90/berserking/g5depwn/
https://www.reddit.com/r/classicwow/comments/cjjcee/how_does_haste_work_in_classic_wow/eve5pq4/

old hunter guide early BC 2007
https://web.archive.org/web/20080913174038/http://hunterguide.wikispaces.com/Theorycraft#GeneralHaste

0f83205d1328f6562117 / 2022-06-06

**Comment by Wall-core** [comment]
Where are you getting the 10% from?

**Comment by ghost** [comment]
idk, ask Kevin Jordan 🙃

> 2019-7-17 Sixx (Server Dad & CEO):
I had found out berserking was giving more haste than expected. The tooltip from vanilla says 10% to 30%, however the actual observed haste was 10% to 43%~. Basically meaning the 10% is constant, then you get an additional 1-30% multiplied to that 10% based on health from 40% to 100% health.

https://classic.wowhead.com/spell=20554/berserking
10-43%

https://classic.wowhead.com/spell=26296/berserking (warrior)
https://classic.wowhead.com/spell=26297/berserking (rogue)
10-30%

**Comment by NickTyrer** [comment]
Maybe related
https://github.com/vmangos/core/issues/663

**Comment by ghost** [comment]
`1.43⁻¹ = 0.7`
`3 × 0.7 = 2.1`
misleading tooltip?

comment from 2012 during Cataclysm:
> If your spell is 2.0 and you have 20% haste from gear that would make it 1.6. If you use Berserking then you'll have it changed to 1.28 and if you had Bloodlust then it would go from 2.0 to 1.2 (Bloodlust is counted first), and using Berserking makes 1.2 to 9.6 second cast. In short: **Berserking takes your finished spell (after gear and buffs) and reduces it by 20%.**

**Comment by Wall-core** [comment]
It's the way that haste is calculated in vanilla. Haste is multiplicative, not additive, and diminishes with multiple sources. The same functions for flurry/kiss of the spider, which you can test. I'll leave the issue open in the tracker for now
