### ISSUE TITLE
gnomish death ray

### ISSUE THREAD

**Issue by gigachadbro** [Wall-core/Everlook-Bugtracker#120]
hey , my enginnering trinket isnt working , gnomish death ray , i dont know why ..... i connect i never use it and it still dont want to work despite i reequip it XD 
![image](https://user-images.githubusercontent.com/46192630/188331645-87356a43-472a-43ee-9825-e2df076282a3.png)

**Comment by Wall-core** [comment]
some items cannot be used after equipping; their cooldown is triggered by equipping but is not shown clientside
