### ISSUE TITLE
Not all of Arugal's Voidwalkers aggro on the player when they are summoned

### ISSUE THREAD

**Issue by Pluuf** [Wall-core/Everlook-Bugtracker#121]
![image](https://user-images.githubusercontent.com/66675502/188440488-afb4e3bc-5ed7-4ea1-89ff-0d3d3e687cc3.png)

Only these two hostile voidwalkers instantly attacked me, the other two didnt attack on summon.

Here a video of the script on another server, all of the four voidwalkers were spawned, all four attacking the party. 

https://youtu.be/nuIP8Z1us-w?t=1987

**Comment by Wall-core** [comment]
I need footage from classic. None of the voidwalkers automatically aggro; it's only because you're level 60 and they're 24 that they don't aggro you if you're not on top of them. Show me footage of classic where they automatically aggro and I'll change it.
