### ISSUE TITLE
Mr. Smite stands there, menacingly, but doesnt walk over and whacks me

### ISSUE THREAD

**Issue by Pluuf** [Wall-core/Everlook-Bugtracker#122]
Hi!

So I aggroed Mr Smite and killed the adds, but Mr Smite doesnt walk all the way to me:

![image](https://user-images.githubusercontent.com/66675502/188473773-5276b63a-d9b8-4da3-a89f-54f569d09109.png)

**Comment by Wall-core** [comment]
mmap issue with that exact spot you're standing, mobs can't path there from the ramp for some reason
