### ISSUE TITLE
warlock & blackout

### ISSUE THREAD

**Issue by ownerdadgamer** [Wall-core/Everlook-Bugtracker#130]
Is everything okay with the warlock spell coefficients I feel like they are doing over the top damage with t2/r13 gear i played warlock through the whole duration of vanilla classic had everything in the game etc u can wear but that was vanilla classic client, I have videos of me doing damage in pvp/pve and the numbers I see there on my screen accounting debuffs and damage amplifiers are like the ones warlocks are doing with full tier 2 sometimes even less. 
2. Blackout seems to procing like crazy on the ptr in duels/warsongs I played I'm not sure still if that is 1.12 vanilla client thing but I haven't seen something like that

**Comment by Wall-core** [comment]
This project reimplements negative spell resistance; warlock curses can push your resistance into the negatives, which amplifies damage taken by the target significantly. This is how it worked pre-1.7, and is unique to this project so you're probably not used to it.

2. Blackout is 10%. Some people might have additional means of proccing it (shadowguard, blade of eternal darkness, etc)
