### ISSUE TITLE
DM North Tribute, too high mana reg.

### ISSUE THREAD

**Issue by luderr** [Wall-core/Everlook-Bugtracker#133]
Issue/bug:
Cho'rush Shaman / Priest version, have too high mana reg and heals way to frequently. The mana reg on Classic and from previous private servers was much lower, it was possible to solo DM Tribute runs as a hunter before.  That's how I made gold on both LH and on Classic. That's why I felt I wanted to contribute. With this high mana reg it is only possible to do if the Mage version spawns. 
This has always been possible to do on pservers and on classic, some people prefer to farm their gold this way.

Thanks, 
can't wait for offical release.

**Comment by Wall-core** [comment]
He's been nerfed to make it possible to solo farm; However you need to keep viper sting up at all times on him now. It's possible to do, but more difficult.
