### ISSUE TITLE
Mobs walking on Objects

### ISSUE THREAD

**Issue by ronaldofenomeno** [Wall-core/Everlook-Bugtracker#134]
![image](https://user-images.githubusercontent.com/33092150/190707174-025a5b62-ee19-4be9-a11d-031e92b66be9.png)

31, 89

=====================================

![image](https://user-images.githubusercontent.com/33092150/190707582-4073799a-7a1d-4524-a067-be7daa02217a.png)

26, 92

====================================

![image](https://user-images.githubusercontent.com/33092150/190707979-25edb0de-b1c7-464a-8773-5af8d904eee1.png)

35, 65

============================
![image](https://user-images.githubusercontent.com/33092150/190708266-a2074a21-314f-4722-8cad-32e2a04cb436.png)

the bandit and bear walk on top of the wagon

46,76

=============================

![image](https://user-images.githubusercontent.com/33092150/190711458-c98acbfc-1709-4e20-9eeb-9c4ef5d34260.png)

86,17

**Comment by ronaldofenomeno** [comment]
I find many NPCs walking on objects throughout the world

**Comment by Wall-core** [comment]
mmaps are fixed next update
