### ISSUE TITLE
Mobs not wandering

### ISSUE THREAD

**Issue by ronaldofenomeno** [Wall-core/Everlook-Bugtracker#135]
I've noticed alot of rockhide boars in elwynn forest that stuck in place and dont wander around

![image](https://user-images.githubusercontent.com/33092150/190709778-ca2852d5-3024-4dd2-86a0-816817c49380.png)

![image](https://user-images.githubusercontent.com/33092150/190709839-0c70f7f5-896b-4608-b60d-aa2af36a46cc.png)

![image](https://user-images.githubusercontent.com/33092150/190709910-cba86b74-005b-4e3b-b0f0-600269a08345.png)

and many others

**Comment by ronaldofenomeno** [comment]
![image](https://user-images.githubusercontent.com/33092150/190711873-a697bf63-bbf7-4984-adbc-f2bfc0e8b21b.png)

more mobs stuck in their place

**Comment by Wall-core** [comment]
Some mobs don't wander. Those sniffs are taken from classic.
