### ISSUE TITLE
Rexxar aggro on aliance

### ISSUE THREAD

**Issue by ghost** [Wall-core/Everlook-Bugtracker#14]
On the dev-server Rexxar and Misha aggro to aliance if you get to close, In classic they didn't aggro.
In classic Rexxar is skull level, on the dev-server he is 62

**Comment by Simp-N** [comment]
Can confirm that he aggroes allies who are just running by
![Sorted_WoWScrnShot_220626_211014](https://user-images.githubusercontent.com/75734743/176154305-4086889e-1d18-44b4-8774-a531ed2e8ccc.png)


Some comments from vanilla-era on [Wowhead](https://classic.wowhead.com/npc=10182/rexxar#comments) mention that he does not attack allies (unless attacked first of course):
> he is red to Alliance but he doesn't attack, i walked with him a lot of times'

>lol lvl 35 human paladin (me) ran past him about 30 mins ago and he did nothing.
