### ISSUE TITLE
Ironforge elite patrollers (Thief Catcher Thunderbrew etc) are running instead of patrolling slowly

### ISSUE THREAD

**Issue by Pluuf** [Wall-core/Everlook-Bugtracker#142]
Made some videos, were too big for github :( 
so here is a screenshot, but they are running:
![image](https://user-images.githubusercontent.com/66675502/190994020-af8444a6-c229-41c7-a206-465ffc9db9b3.png)

**Comment by Wall-core** [comment]
He's walking on the server. could've been him catching up to pathing because of enemy
