### ISSUE TITLE
Curse of Recklessness does not immune fear.

### ISSUE THREAD

**Issue by syyckfryyk** [Wall-core/Everlook-Bugtracker#144]
People still get feared with CoR on. They do retain full control of their characters but fear debuff is still present. The warlock can then switch to another curse which enables the same fear to start functioning. Putting on CoR again renders the fear ineffective again without removing the debuff.

**Comment by Wall-core** [comment]
This is blizzlike; the debuff is not canceled but disabled while curse is active, allow you to control fear with greater skill.
