### ISSUE TITLE
beasts should not drop mining gems as part of their loot table.

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#147]
![loot table messed up beasts dropping gems](https://user-images.githubusercontent.com/35550935/192129739-e9570c97-db4f-4cd5-bd19-29446a41a21e.png)

beasts loot table messed up.  animals should not have gems in their loot table. (shadowgem) dropped from wolf in duskwood.

**Comment by FlagFlayer** [comment]
Beasts are supposed to drop gems. Looking at the comments at https://classic.wowhead.com/item=1210/shadowgem#comments there have been many instances of beasts dropping Shadowgems in vanilla.
