### ISSUE TITLE
Neutral mob aggro

### ISSUE THREAD

**Issue by prytzi94** [Wall-core/Everlook-Bugtracker#150]
Hi, 

When I aggro a neutral mob besides another neutral they both aggro even though I only hit one of them.

Happend with the rockjaw troggs in Dun morogh, maybe something special with them?

**Comment by munkyhub** [comment]
I can confirm this issue. Happend to me with troggs in Dun Morogh multiple times.

**Comment by Wall-core** [comment]
Need video evidence of mob linking behavior from classic before I can fix.

**Comment by cloudbells** [comment]
See #169

**Comment by Pluuf** [comment]
The mobs are yellow, meaning that if you aggro one, the others shouldn't do anything. I had the same issue on the troggs today and the yellow ones should not link. Would you accept footage from another pserver? Because then I can check the behaviour on Darrowshire for example.
