### ISSUE TITLE
Very low drop rates on grey gear in starting zone(s?)

### ISSUE THREAD

**Issue by cloudbells** [Wall-core/Everlook-Bugtracker#152]
While leveling in Northshire in Classic and SoM, drop rates for gray items like [Frayed Belt](https://classic.wowhead.com/item=3363/frayed-belt) are way higher than on Everlook. Can't confirm this and this might be bias but I think 6-slot bags might have a higher drop chance here than in Classic.

**Comment by Wall-core** [comment]
Drop rates are sniffed, you're probably just unlucky

**Comment by cloudbells** [comment]
No, but it might've been fixed since this issue was created. I'll level from 1-6 on both Classic and Everlook and compare results.

The low drop rates led to significantly lower money early levels.
