### ISSUE TITLE
[Client issue] Enabled windowed mode - black screen

### ISSUE THREAD

**Issue by readlisten** [Wall-core/Everlook-Bugtracker#153]
Enabled Windowed Mode in Video Settings, now the window is completely black. I hear audio as usual.
First time this happened, I uninstalled and reinstalled the client in order to be able to play again. Alt-tabbing out then back in did not restore functionality. Neither did closing the game/program and relaunching--even the login screen was completely black.
This time, the completely black screen seems intermittent. Only once, alt-tabbing out then back in restored functionality. Every other time, alt-tabbing out of the game then back in does not help. Closing the game and relaunching does not appear to help.

**Comment by cloudbells** [comment]
This is a client issue and shouldn't be posted here. [This](https://forum.warmane.com/showthread.php?t=403829) could maybe help?

**Comment by readlisten** [comment]
Ah, thank you for the pointer. My mistake
