### ISSUE TITLE
No dynamic respawns on world objects

### ISSUE THREAD

**Issue by cloudbells** [Wall-core/Everlook-Bugtracker#154]
Might be only [this](https://classic.wowhead.com/quest=3904/millys-harvest) quest, but the [Milly's Harvest](https://classic.wowhead.com/object=161557/millys-harvest) objects respawned very slowly even with 20-30 people around the vineyard.

**Comment by Razorkin** [comment]
> Might be only [this](https://classic.wowhead.com/quest=3904/millys-harvest) quest, but the [Milly's Harvest](https://classic.wowhead.com/object=161557/millys-harvest) objects respawned very slowly even with 20-30 people around the vineyard.
There are more quests that don't have a dynamic respawn timer such as [The stolen tome](https://classic.wowhead.com/quest=1598/the-stolen-tome) Although there aren't many warlocks around but it is still a small hiccup. 
I'm pretty sure there will be more of those during ptr

**Comment by Wall-core** [comment]
Game objects do not have dynamic spawns; this is not a simple config option, and I will have to go through all low level quest objects at launch to adjust for better gameplay.
