### ISSUE TITLE
Warlock pet doesnt shoot

### ISSUE THREAD

**Issue by Adlertopf** [Wall-core/Everlook-Bugtracker#161]
My imp doesnt auto-attack when im attacked and its on defense mode, and the aggressive mode doesnt work either. if i click the "attack" button or use the keybind, it doesnt do anyhting either. the onlny thing to get it to do anyhting is to manually click on the firebolt or other spells

**Comment by Wall-core** [comment]
Player error; turn on autocast for his fireball spell.
