### ISSUE TITLE
i died in night's web hollow to skip the walk back and my soul appeared in brill

### ISSUE THREAD

**Issue by ohktry** [Wall-core/Everlook-Bugtracker#178]
i died in the in the bifurcation not even deep in the cave

**Comment by ohktry** [comment]
another bug, tried to walk back and ress in the starting area and got tp back to brill

**Comment by ohktry** [comment]
another bug, i was typing here and somehow i got back to the shadow grave

**Comment by Wall-core** [comment]
Graveyard locations for starting areas are corrected next update; attempting to rez at a different spirit healer sends you back to original corpse zone.
