### ISSUE TITLE
Fungal Spores, at the forgotten pools

### ISSUE THREAD

**Issue by grisker** [Wall-core/Everlook-Bugtracker#179]
The fungal spores respawn rate is wrong/broken. I've set my timer and only have seen 1 mushroom for the past 10 minutes. Usually each  mushroom node has its own timer but it seems this time is connected with all of them or something.

**Comment by Wall-core** [comment]
They respawn every 3 minutes, which is blizzlike.

**Comment by grisker** [comment]
Does that mean you are going to fix the issue? This quest is hard to skip because the reward is really important
