### ISSUE TITLE
PLEASE fix swimming for this server :P

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#18]
I should be able to (when underwater) use the space bar (jump) to float up.. and the "X" key (sit command) to float down.

It works in classic but have yet to find a Pserver that is willing to make this work as intended <3

*Elf flips underwater does not look right when I'm coming up for air...

**Comment by ratkosrb** [comment]
That is client side and has nothing to do with the server. That is how underwater movement works in the 1.12 client.
