### ISSUE TITLE
mana / health pots at Alchemy vendors

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#19]
In classic these vendors sold limited number of level apropriate alchemy potions. Mana pot and health potions

also some rare recipies like FaP on a respawn

see picture (Darnassus)
![potions and such 01](https://user-images.githubusercontent.com/35550935/177014983-c907094a-5361-4613-8fb5-3569ccc67efa.png)

**Comment by hgarner17** [comment]
disregard FaP recipe. it's clearly there in the picture. just missing mana pot and health pot (lvl 3)

**Comment by NickTyrer** [comment]
He has the correct vendor table.
