### ISSUE TITLE
If wow kicking you from server due AFK - settings not saved (like you did Alt-F4) - is it intended?

### ISSUE THREAD

**Issue by laytya** [Wall-core/Everlook-Bugtracker#192]
experience it many times already - actionslots not saved etc....

**Comment by laytya** [comment]
Not only settings, its also rollback me (some quest i made - rolled back)

**Comment by Pluuf** [comment]
If you do not properly exit your client your UI updates won't be saved, that's as intended. So exit properly to have that saved.

And the character save on the database has been increased to 1x pwr minute, so this issue seems to be done.

**Comment by laytya** [comment]
Do you read bug? Read title!

**Comment by Wall-core** [comment]
> If you do not properly exit your client your UI updates won't be saved, that's as intended. So exit properly to have that saved.
> 
> And the character save on the database has been increased to 1x pwr minute, so this issue seems to be done.

this is correct

**Comment by laytya** [comment]
You just dont understand problem - Its server close connection not me. So its auto kicking from wow. I cant control "PROPERLY EXIT".
