### ISSUE TITLE
Starting zone bag drop rate seems much higher than Classic

### ISSUE THREAD

**Issue by cloudbells** [Wall-core/Everlook-Bugtracker#196]
This needs more evidence, but so far I have leveled twice on Everlook to 8 and 6. The first time I left Northshire with 2 bags and the second with 4 bags (I only have video evidence of the second time, see: https://youtu.be/GuTdSBVzWTM?t=5375).

Compare with Classic, I will very rarely leave the starting zone with even one bag. See https://youtu.be/GuTdSBVzWTM?t=2458).

**Comment by Kantrul** [comment]
Maybe it's because the server is in patch 1.4 right now?
