### ISSUE TITLE
SW Sewer Beast (Big Croc) is static should be on pat

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#20]
The large *skull* Sewer Beast is static in SW
I believe in Classic it swims about

![SW Sewer Beast Big Croc Static](https://user-images.githubusercontent.com/35550935/177016825-6a626862-4fe4-4c92-9fe3-54aedec6cc02.png)

**Comment by ratkosrb** [comment]
We have 29 sniffs of this mob, and it has not been seen moving in any of them. It does have several spawn locations however.
