### ISSUE TITLE
Poor old Blanchy

### ISSUE THREAD

**Issue by Avelorian** [Wall-core/Everlook-Bugtracker#205]
Hello!
In Westfall there are no Sack of Oats for quest Poor old Blanchy.
https://classic.wowhead.com/quest=151/poor-old-blanchy

**Comment by Avelorian** [comment]
Correction: they are exist, but dont respawn after looting.

**Comment by NickTyrer** [comment]
They are pooled, so they respawn in different areas of westfall.
