### ISSUE TITLE
bubbling fissure

### ISSUE THREAD

**Issue by Chattex** [Wall-core/Everlook-Bugtracker#206]
![ScreenShot_100922_120123](https://user-images.githubusercontent.com/7826580/194771309-7e3f3de6-9153-440c-8f50-9a34a34bd0d7.jpeg) 
Bubbling fissures dos not refile our breath bar

**Comment by NickTyrer** [comment]
Unfortunately we can't get the server side gameobject trap for this object to enable waterbreathing. All other bubbling fissures work correctly though.
