### ISSUE TITLE
lvl 8 rockhide boar crits for 82

### ISSUE THREAD

**Issue by dinochange** [Wall-core/Everlook-Bugtracker#207]
as you can see normal hits of this boar are 14-16, but i got one crit for 82!!! seems a bit much. not sure if this was working this way in classic
![image](https://user-images.githubusercontent.com/42609072/194771707-b5ac283b-cca7-4ef8-84f7-c92e3cc23452.png)

**Comment by selmira** [comment]
Was it the first hit of the Boar? I'm pretty sure their first hit gets a massive attack power bonus after they charge you. Should see again if it was after charge or a regular crit.
