### ISSUE TITLE
invisible NPCs in some buildings, targetable but uninteractible, major issue

### ISSUE THREAD

**Issue by lovropepelko** [Wall-core/Everlook-Bugtracker#208]
![image](https://user-images.githubusercontent.com/47788656/194772695-b6e8e672-fa79-4241-9382-be6e559468e2.png)

**Comment by lovropepelko** [comment]
most likely client side issue. this happens in kronos client, in elysium client its perfectly fine

**Comment by Razorkin** [comment]
delete WDB folder

**Comment by GomOnHyjal** [comment]
I'm having the same issue using the Nostalrius client. Deleting the WDB does not make the NPCs reappear, only works when I relog.

**Comment by josip90** [comment]
same with me, /reload doesn't fix. 
i have to turn off game completely then start again..
p.s. deleting WDB folder also doesn't help

**Comment by mutebat39** [comment]
I noticed that if I rotate my camera, sometimes the disappeared NPCs come back into view, most frequently if I look directly _away_ from them so my back is facing them. These NPCs also are usually visible until I cross a threshold into a building, ex. I can walk straight into the Razor Hill inn and see the innkeeper from the outside, all the way until I walk into the building, then shortly after actually entering the building, he disappears. Given that rotating the camera around often (but not always) can make these NPCs reappear, it almost feels like a line-of-sight problem.

Walking into buildings also doesn't always cause NPCs to disappear. Conversely, I've never seen NPCs disappear (at least so far) while wandering around in the open world outside of any buildings. Relogging also fixes the issue temporarily, but deleting the WDB folder doesn't seem to have any effect.

Not sure what client I'm using (glad to report that if someone knows how to identify them) but I am running the client on Wine on Linux. I used this same client on Darrowshire (albeit running on Windows) and never saw this issue on there.

**Comment by Wall-core** [comment]
> I'm having the same issue using the Nostalrius client. Deleting the WDB does not make the NPCs reappear, only works when I relog.

you cannot delete your wdb without closing your client, so I don't get what you mean by this

**Comment by Wall-core** [comment]
this issue has been posted 17 times in the last week; please read through the bugtracker to confirm you aren't posting the same issue the 18th time. it will be fixed, it is simply due to render distances being high here and affecting some hardware settings.
