### ISSUE TITLE
Pet Attack Macro not working

### ISSUE THREAD

**Issue by jerdrb** [Wall-core/Everlook-Bugtracker#211]
Currently attempting on warlock to command my imp to attack, thus causing it to use its autocast spell. No response from imp occurs. Imp will attack if using direct cast macro.
Doesn't work: /petattack
Does work: /cast Firebolt

**Comment by Simp-N** [comment]
/petattack is a Classic macro. You'll want macros for vanilla 1.12.1.

Try ``/run PetAttack()`` and ``/run PetFollow()`` instead
