### ISSUE TITLE
Changed Charge path angle

### ISSUE THREAD

**Issue by ronaldofenomeno** [Wall-core/Everlook-Bugtracker#212]
My character changed path angle mid-charge

https://youtube.com/clip/UgkxNqguaF1QQMrqMZmItd0RAu05KBNwpIzz

**Comment by ronaldofenomeno** [comment]
wanted to mention this happened to me twice in that area. the second time it happened I was in 55,63

**Comment by Wall-core** [comment]
that is pathing, and looks fine to me.
