### ISSUE TITLE
Garments of the Light

### ISSUE THREAD

**Issue by MUTTER1990** [Wall-core/Everlook-Bugtracker#216]
Priest quest not working correctly. Healing the dwarf does not count as healed in the quest, only the Fortify gets updated
![image](https://user-images.githubusercontent.com/115388110/194799101-f13162b2-e227-44c3-beb5-cb39e881b142.png)

**Comment by NickTyrer** [comment]
It worked for me, did you heal with rank 2 then cast fortitude?

**Comment by MUTTER1990** [comment]
Yes, for it to work I had to relog and it was then marked as completed
