### ISSUE TITLE
Group Loot in Dungeons

### ISSUE THREAD

**Issue by TheRealTilon** [Wall-core/Everlook-Bugtracker#221]
After killing Edwin Van Cleef we rolled on his loot (which I've won), but my inventory was full so I wasn't able to pick it.
While I was corpse running, my friend looted Edwin, and managed to actually get the sword that I've technically won.
Also to mention that it was a BoP item, we ended up without any possibility to get that sword back in my inventory.

**Comment by ratkosrb** [comment]
That is intentional behavior in the code. Back on LH there was an argument if it was a blizzlike vanilla bug or not and I remember Guybrush had made a PR to "fix" it, but in the end it wasn't changed.
