### ISSUE TITLE
First spawned patrol in Deadmines

### ISSUE THREAD

**Issue by TheRealTilon** [Wall-core/Everlook-Bugtracker#222]
In Deadmines, the patrols that appears once you kill a boss must spawn from behind, slowly coming to you.
This is the case for all the patrols EXCEPT the first one, which spawns in the middle of the doors, a bit behind it;  between the initial place of Rhahk'Zor and the following adds.

**Comment by Wall-core** [comment]
never heard of this happening. Can you show me with some pictures or video where he's spawning?
