### ISSUE TITLE
Entangling Roots considered indoors when outside + MANY issues with Durnholde

### ISSUE THREAD

**Issue by FlagFlayer** [Wall-core/Everlook-Bugtracker#223]
Multiple places of this, but I specifically pinpointed the structure in the Sludge Fen and the bridge after the entrance to Durnholde Keep as examples. I'm not certain if it's intended or not for Entangling Roots to not work in these palces, but considering the fact they are CLEARLY outside I'm not sure why this would be the case.

May be a VMangos issue, needs testing.

**Comment by FlagFlayer** [comment]
In general Drunholde seems incredibly buggy with pathing, many mobs dragging random other mobs randomly. Shadow mages also cast a curse that is very ovetuned, dealing a massive amount of damage to any class with fast attack speed (this is post nerf, 50% to inflict 60 shadow damage every hit on fast attack speed is ridiculous). Overall the subzone needs a TON of attention since things are very broken here.

**Comment by FlagFlayer** [comment]
Another issue with Syndicate Watchman hitting me with what I'm assuming was an ability after it was already dead.

**Comment by FlagFlayer** [comment]
The outdoor inner keep area is also considered indoors, unsure if it's correct.

**Comment by stairl3k** [comment]
Searing Totem doesn't seem to aggro properly in sludge fen either

**Comment by FlagFlayer** [comment]
Probably wouldn't in Durnholde either then, but needs testing.

**Comment by Wall-core** [comment]
> The outdoor inner keep area is also considered indoors, unsure if it's correct.

the whole keep is a WMO and is flagged as indoors. There's no fix for this outside of custom patch. as for pathing, that will be fixed next update
