### ISSUE TITLE
Tradeskills Trainers Flavor Text

### ISSUE THREAD

**Issue by ohmygoshoctopus** [Wall-core/Everlook-Bugtracker#226]
The text in the dialog with tradeskills vendors acts as if you are level 150: "your skill exceeds that of mine..." This was true for the Fishing and the Cooking vendors in Mulgore, with fishing/cooking skills of 0 and 1.

**Comment by NickTyrer** [comment]
They have the correct gossip in vmangos. Please delete your WDB and try again.

**Comment by NickTyrer** [comment]
Confirmed to have wrong gossip in everlook PTR.
