### ISSUE TITLE
Fishing Bobber Animation

### ISSUE THREAD

**Issue by ohmygoshoctopus** [Wall-core/Everlook-Bugtracker#228]
The fishing bobber animation is more abrupt than usual; it kinda jumps under the surface and then hops back up.

**Comment by MoopTheDruid** [comment]
Same issue here. The floating animation can do anything from just dropping a frame to playing the entire bob and splash animation. Tough to tell if you've hooked a fish sometimes.

**Comment by Wall-core** [comment]
1.12 client issue, unrelated to server
