### ISSUE TITLE
Some Sound Effects Too Quiet

### ISSUE THREAD

**Issue by ohmygoshoctopus** [Wall-core/Everlook-Bugtracker#229]
Two different effects were much quieter than I'd expect; they were impossible to hear in the rain until the sound values were adjusted to their next-to-extremest values. Footfalls and the fishing bobber were the effects observed. In fact, I thought footfalls were not on at all, until I turned the rain off completely. This was in Mulgore. Most other sound effects - casting Wrath, squealing pigmen, Moonfire's "explosion" - all came through at normal volumes.

**Comment by Wall-core** [comment]
1.12 client issue, not server related
