### ISSUE TITLE
timberling spawns lvls 5 and 6

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#23]
There are at least 4 spawn locations missing for timberlings lvl 5 and 6 in Teldrassil just south of Lake Al' Ameth

these mobs are a bottleneck point (for their seeds) at launch and not having these mobs here will hurt launch smoothness

should be lvl 5 or lvl 6 timberlings placed exactly on the X
![timberling spawn locations](https://user-images.githubusercontent.com/35550935/177214754-144e4e87-866f-4f8d-929e-5c3475baed54.png)

**Comment by hgarner17** [comment]
Original picuture is here.. of the empty spawns
![Missing mobs for quests elf lands](https://user-images.githubusercontent.com/35550935/177215486-5cee599e-7204-4d48-a869-4f06a3942ffe.png)

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1483
