### ISSUE TITLE
No Loot = Not Lootable

### ISSUE THREAD

**Issue by ohmygoshoctopus** [Wall-core/Everlook-Bugtracker#230]
When a mob dies and (I assume) has no loot on it, the mob is not lootable at all, as if someone else had tagged the kill. This only happened on level 6 Prairie Wolves in Mulgore. The typical thing would be an opened and empty loot window, which makes a rustling sound and disappears after 0.5 seconds or so on autoloot. After that, the mob would appear unlootable.

I am guessing here as to the nature of the "not lootable" state. It's possible someone else tagged them or something, but the mob target bar was red and not gray.

**Comment by laytya** [comment]
some times it have quest item but u dont have to loot it and its not visible to you. So its 3d state =)
