### ISSUE TITLE
A strange shed wall (not blocking mob aggro sight)

### ISSUE THREAD

**Issue by Dead-beathorse** [Wall-core/Everlook-Bugtracker#234]
There is a shed in Stromgarde Keep (Arathi Highlands) next to Or'Kalar. I have used it multiple times on many servers to hide from mobs (even tested it on level 1 characters). They have never aggroed on me. I am not saying this is a bug on your server, it might be a bug on other servers, but it might be worth checking it out. I'm not sure if this is an issue with all sheds or even that they are supposed to block the mob sight, but it makes sense that it would (but hey, maybe my forsaken character smells of rotten flesh :) )

I will post some photos to prove the fact that at least on a different server the mobs won't aggro.
![Shed 1](https://user-images.githubusercontent.com/115499847/194939398-e2c48929-931b-4dec-b73c-f1faab395d36.png)

![shed 2](https://user-images.githubusercontent.com/115499847/194939409-14b42689-a766-4f1c-89cc-2c06983e1bab.png)
The ones above are from your fine server.

These ones are from a different server:
![shed 3](https://user-images.githubusercontent.com/115499847/194939603-822ca0f5-d565-4c13-a7ad-d23c6d0403f8.png)

![shed 4](https://user-images.githubusercontent.com/115499847/194939619-7d0f7699-9c50-4c84-9609-28223059bc33.png)

![shed 5](https://user-images.githubusercontent.com/115499847/194939631-4cdd1027-cfe2-4d54-a083-ff081605a22e.png)

![shed 6](https://user-images.githubusercontent.com/115499847/194939650-1ed6113b-51b4-46e4-bc21-70442d840b9f.png)

You can see where they aggro on the second server, about at the exist of the shed. As I said, might be worth checking it out. It's just that this is the first time I have seen these ogres behave this way. Maybe it has something to do with the patch?

Thanks for the WoW experience you are giving us and will continue to give us long into the future.

**Comment by Wall-core** [comment]
What servers did you have this happen on? If turtle, it's because they have M2s enabled for LoS which is not blizzlike.
