### ISSUE TITLE
Seek-redemption Quest

### ISSUE THREAD

**Issue by zaph-oh** [Wall-core/Everlook-Bugtracker#236]
Fel Cone spawn rate is extremely low.  Cannot complete quest when only person on it.  Looked all around correct areas. I found 2 right away and then none for 15 minutes.

**Comment by NickTyrer** [comment]
The respawn times are correct in the DB. These objects are now pooled and require more searching to find them. Also I think they will enable dynamic respawn on launch so that should speed things up.

**Comment by Tessablanc** [comment]
There still aren't enough cones. With barely anyone in Teldrassil there are hardly any to be seen. Pooling this quest item is not a good idea, even with dynamic respawn timers. It's a quest you complete while doing other stuff, not a four hour Easter Egg hunt.

**Comment by Wall-core** [comment]
> There still aren't enough cones. With barely anyone in Teldrassil there are hardly any to be seen. Pooling this quest item is not a good idea, even with dynamic respawn timers. It's a quest you complete while doing other stuff, not a four hour Easter Egg hunt.

The pooling is blizzlike. Quest objects will have dynamic respawn timer.
