### ISSUE TITLE
Can "loot" a dead mob an infinite number of times

### ISSUE THREAD

**Issue by poofffaa** [Wall-core/Everlook-Bugtracker#237]
If I shift + right click a corpse, it will say I got the money from it, and play the little looting sfx.
That's normal, but if I move my character instantly after shift + right clicking, the looting will be
canceled, but the message saying something like "You loot 4 Copper" will still appear and
the sfx will play. I can do this over and over and spam that message to myself.
I tested this in a group, and it does not spam the message while in a group. I can make the sfx
play over and over for myself but that's it.

**Comment by Wall-core** [comment]
client issue
