### ISSUE TITLE
Fishing Trainer "Lee Brown" in Elwynn Forest incorrect dialogue

### ISSUE THREAD

**Issue by poofffaa** [Wall-core/Everlook-Bugtracker#238]
I haven't even learned apprentice fishing yet but he says "Your skill exceeds mine, though I've heard that Old Man Heming in Booty Bay has copies of "The Bass and You" that is sure to help increase your skill."

**Comment by NickTyrer** [comment]
He has the correct gossip in vmangos. Please delete your WDB and try again.

**Comment by NickTyrer** [comment]
Confirmed to have wrong gossip in everlook PTR.
