### ISSUE TITLE
Invisible Kobolt Miner during "WANTED: Murkdeep!" quest in Darkshore

### ISSUE THREAD

**Issue by GeezyXDenied** [Wall-core/Everlook-Bugtracker#239]
There's an invisible mob that spawns during the first wave of the quest. It is not targetable. Was attacking me during the encounter. All spawned mobs were killed and it continued to attack me - killing me from below the ground. Recleared the camp and no wave came. "The Kobolt Miner" was at the edge of the water and started to attack my pet. See combat log for confirmation.
![Murkdeep](https://user-images.githubusercontent.com/115512797/194972688-2b651bc8-543c-4612-b7d8-c75a75348dfe.png)

**Comment by Wall-core** [comment]
fixed in next update
