### ISSUE TITLE
Honor on targets in combat with NPC's is not being calculated properly

### ISSUE THREAD

**Issue by Roflkopterr** [Wall-core/Everlook-Bugtracker#243]
Mobs that deal damage to players while in combat is taking away from honor being given to the player/s that kill.

If you kill someone who took damage while in combat with a mob or even if they JUST killed the mob and you wait a few seconds for him to eat back to full. It will calculate the honor as though another player did the damage that was dealt by the mobs/npc's and it will split that honor into the calculation. 

So if someone has 100 hp and a mob does 75 dmg to them, combat ends, they eat to full or I kill them right away, in BOTH instances I only get 25% of the actual honor that should be gained.

**Comment by Wall-core** [comment]
Need someone to test this on classic

**Comment by Roflkopterr** [comment]
https://www.youtube.com/watch?v=xESQ8K7ercE 2:30 full honor for half hp targets.
