### ISSUE TITLE
incendia-agave

### ISSUE THREAD

**Issue by Chattex** [Wall-core/Everlook-Bugtracker#250]
https://classic.wowhead.com/item=12732/incendia-agave
incendia-agave should have a 30 sec respawn, it's more than 2 minute in PTR

**Comment by Wall-core** [comment]
"It seems that whenever a plant is looted, another one respawns elsewhere in the area."
It's pooled, loot it from elsewhere to trigger spawn. There's 9 max that are spawned at a time.
