### ISSUE TITLE
Defias Looter with Mage Armour?

### ISSUE THREAD

**Issue by HappySquid89** [Wall-core/Everlook-Bugtracker#252]
One of the Defias Looters behind Alexston's Farmstead gave me the 'Chilled' debuff when I attacked him. It happened 3 or 4 times so.
Can the mobs buff each other or did he mistakenly spawn with a Frozen Armour buff on?

https://imgur.com/a/ODHSMph

**Comment by Wall-core** [comment]
Tested and couldn't replicate. Looks more like you did some damage to a defias pillager who had it up

**Comment by HappySquid89** [comment]
It only happened with this mob and I made sure I wasn't in combat with anyone else. I kept fighting it and it applied a total of 3 times. But I'm not that familiar with Vanilla anymore, so maybe it was my fault. It's a very minor thing anyway.
Thanks for looking into it!
