### ISSUE TITLE
The Power to destroy Quest

### ISSUE THREAD

**Issue by Gungar11** [Wall-core/Everlook-Bugtracker#254]
We just did RFC and only one of the books dropped, not the ''Incantations from the Nether''.

It's the first time in all of my WoW experience that this quest did not complete in one run. Something seems off in either the drop chance or a bug that contributed to it not dropping.

We cleared the whole dungeon. Not one mob was alive.

**Comment by Roflkopterr** [comment]
Several of us did this on PTR with no problem. It IS possible that you can do a whole clear and not get both books I have seen it happen before.

**Comment by Wall-core** [comment]
Yeah just bad luck.
