### ISSUE TITLE
Weapon Skill Increases sometimes skip one point

### ISSUE THREAD

**Issue by Iskato** [Wall-core/Everlook-Bugtracker#259]
I am currently leveling an orc warrior and when I switched to a 1h axe, i realized when skilling up that sometimes it jumps up by 2 values at once. Couldn't try it on other weapon types yet - maybe others have experienced similar.
![Screenshot1](https://user-images.githubusercontent.com/115587045/195185753-787ca7e8-7726-47f8-847a-2ef52514068a.png)
![Screenshot2](https://user-images.githubusercontent.com/115587045/195185757-19efc74f-c3b9-4eff-a9dc-c9aa4075d281.png)

**Comment by Iskato** [comment]
Tried to reproduce the issue with Unarmed, but everything worked fine there.

**Comment by Wall-core** [comment]
Config setting, will be changed for live. not a bug.
