### ISSUE TITLE
Webwood Lurkers are not supposed to shoot spiderwebs

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#26]
the rooting attack of Webwood lurkers shooting spider webs is not correct.
(most pservers get this wrong) in classic and in SoM these mobs (lvl 5 and 6) do not shoot webs that root players

that is ONLY the lvl 8 and 9 spiders by the mossy tumors quest in the central north (around the lake / river)
![webwood lurkers are not supposed to shoot webs (only the lvl 8 ones closer to the middle north of map do that)](https://user-images.githubusercontent.com/35550935/177215828-6ca696ad-b61f-4391-939b-d2e85b382e68.png)

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1483
