### ISSUE TITLE
"Plagued Lands" quest bugged

### ISSUE THREAD

**Issue by churchvibez** [Wall-core/Everlook-Bugtracker#261]
Rabid Thistle Bear will not be captured by the trap after attempts including: causing no damage to it, causing some damage and running it through the trap, dismissing my pet prior or getting the bear to low HP.

**Comment by sudolink** [comment]
Worked for me. Gif of it working -> 
Had to pull the bear right over the trap. It's sometimes hard to distinguish its pale red glow against the grass. The trap doesn't drop exactly where the char kneels. 
![ezgif-3-5673ce8ced](https://user-images.githubusercontent.com/46523097/195448662-f1b4958e-6c57-44b7-81e7-4e116ade732f.gif)

**Comment by Xazamas** [comment]
My first trap did not work, had to go back and get another and it worked. 

My leading theory is that the bear aggroing my Voidwalker first somehow messed the scripting, 

I also placed the trap on "sand" looking terrain the first time, and to "grass" looking terrain the second time.
