### ISSUE TITLE
Weapon Swap Macro

### ISSUE THREAD

**Issue by hanahaki0824** [Wall-core/Everlook-Bugtracker#264]
Weapon swap macros by using /equip works for MH and 2H weapons but doesn't work for shield. Even when just taking the weapon out of the macro and making an individual /equip macro for shield it doesn't work. Not a high enough level to test if it works for OH weps yet but I would imagine that wont work either.

**Comment by Wall-core** [comment]
You're using 1.14 client macros; google 1.12 macros because they're totally different.
