### ISSUE TITLE
Razzle Spryprocker disappearing at close distance - Kharanos

### ISSUE THREAD

**Issue by LunarHermit** [Wall-core/Everlook-Bugtracker#265]
![Captura de pantalla (45)](https://user-images.githubusercontent.com/115593226/195208682-62aea26a-97b4-4622-92e9-e605de5abf3f.png)
![Captura de pantalla (46)](https://user-images.githubusercontent.com/115593226/195208740-22e3f66f-0172-4a58-8cc0-1343f565caff.png)
![Captura de pantalla (47)](https://user-images.githubusercontent.com/115593226/195208783-2bf5a80e-ab55-48ef-ab4c-e5815f333db9.png)

**Comment by Wall-core** [comment]
Relogging solves the issue.
