### ISSUE TITLE
"Verog the Dervish" quest seems bugued.

### ISSUE THREAD

**Issue by WanAutumLeaf** [Wall-core/Everlook-Bugtracker#267]
The quest requires you to go where the centaur mob named "Verog the Dervish" (near the stagnant oasis in the barrens), once there you have to kill centaurs near the hut where Verog spawns until Verog apears yelling something about being challenged.

Issue: After more than 15 minutes killing centaurs close to the mentioned spot (Hut where Verog spawns), more than 5 mob respawn cicles and even pulling further centaurs into the "Verog's spot" to kill them there, Verog still hasn't spawned. 

It's a quest where the time needed to "summon Verog the Dervish" vary, sometimes taking 3 kills sometimes taking 15. But after so much time killing centaurs near the spot Verog still has not appeared, it definetly seems that the quest isn't working.

**Comment by Wall-core** [comment]
The quest works, it just takes about 50 kills in early progression.

**Comment by WanAutumLeaf** [comment]
That's just insane, the zone has 3 centaurs near the hut and like 3 or 4 around. Thanks for clarifying tho, will avoid that quest.
