### ISSUE TITLE
"Kolkar Bloodcharger Centaur" mobs not casting corruption.

### ISSUE THREAD

**Issue by WanAutumLeaf** [Wall-core/Everlook-Bugtracker#268]
Based on my previous private server experience and my WoW Classic and WoW TBC Classic experience the mobs in the barrens called "Kolkar Bloodcharger" casted corruption on their hostile target during combat, in the PTR the act pretty much like the mob "Kolkar Marauder", they just run into the hostile target and mele attack them.

**Comment by Wall-core** [comment]
They do
![image](https://user-images.githubusercontent.com/90075138/195243018-9f8f95d9-7619-4bec-b29d-4d8e903d7445.png)

**Comment by WanAutumLeaf** [comment]
My apologies, I went back to check it out (since in the SS appears Herul bloodmark) and indeed they cast corruption.

Although in the PTR if i tank them by healing they take always a while to cast corruption and if i keep tank-healing them they tend to spam corruption often until they go oom (and while I still have 5+ seconds left in the current corruption debuff on my character). 

I remember that in Classic this centaurs casted corruption on agro and then came to fight mele combat, once the corruption debuff droped they tried to refresh it.

Sorry for disturbing you, I tought it was worth mentioning, thanks for your work and answering so fast.
