### ISSUE TITLE
Clearcasting / Elemental Focus

### ISSUE THREAD

**Issue by Jaguadarte1999** [Wall-core/Everlook-Bugtracker#269]
I don't know if this is the way that it works but Groud Tot procs it. Flame/Frost weap procs are procin clearcasting.
Another issue with it is that clearcasting is beeing consume before I cast a skill, when the skill land on target.

**Comment by Wall-core** [comment]
Clearcasting procs on elemental weapon damage from shamans here, it's an old private server mechanic which was readded. This applies to things such as storm gauntlets, blazefury medallion, flametongue weapon and damaging weapon procs (including enchants such as fiery). With storm gauntlets, flametongue and blazefury alone you have 30% chance to proc clearcasting on melee, which makes both elemental and enhancement shamans playable in pve.

This mechanic applies as well to paladin's Vengeance talent, mage's Ignite talent, and Warrior's and Shaman's Flurry talent (with physical weapon damage procs like Jeklik's which can trigger physical damage crits to proc it).

I don't know what would be consuming it; playtesting has shown clearcasting to work perfectly fine. Submit video evidence if you believe that something is bugged.

**Comment by Jaguadarte1999** [comment]
![image](https://user-images.githubusercontent.com/115602358/195242409-b019c626-2c13-4345-a0ca-13c6d0a82cf9.png)

**Comment by Jaguadarte1999** [comment]
I gain when spell is launch and fades when spell land I'll try filming it somehow :)

**Comment by Jaguadarte1999** [comment]
https://www.youtube.com/watch?v=fKq58_FTRZs 
There we go :) 
22 secs
