### ISSUE TITLE
Tab Target Distance Too Low

### ISSUE THREAD

**Issue by ohmygoshoctopus** [Wall-core/Everlook-Bugtracker#274]
The tab target distance is set to something like 35y. I think it's supposed to be more like 40. It certainly feels too short. The angle on the tab targets - the cone in front of the character - feels great.

**Comment by Simp-N** [comment]
I believe this can be changed by editing the config.wtf file in your WTF folder.
``SET targetNearestDistance "40"``

or in-game with ``/console targetNearestDistance 40`` but I'm unsure if changing it in-game keeps the change when exiting the game.

**Comment by Wall-core** [comment]
> I believe this can be changed by editing the config.wtf file in your WTF folder. `SET targetNearestDistance "40"`
> 
> or in-game with `/console targetNearestDistance 40` but I'm unsure if changing it in-game keeps the change when exiting the game.

correct. this is all client side, has nothing to do with server.
