### ISSUE TITLE
Conjure Water Tooltip Doesn't Update With Level

### ISSUE THREAD

**Issue by ohmygoshoctopus** [Wall-core/Everlook-Bugtracker#275]
The tooltip for Conjure Water does not update the number of bottles conjured as your level advances, although that many bottles do actually conjure.

**Comment by Wall-core** [comment]
Client side, deleting wdb may fix.

**Comment by ohmygoshoctopus** [comment]
Deleting WDB did not fix it. I am still having the same error.
