### ISSUE TITLE
Ooze-Covered Gold Vein by Senjin Village

### ISSUE THREAD

**Issue by sudolink** [Wall-core/Everlook-Bugtracker#281]
loc: 50.4, 74 in Senjin Village

not sure if vmangos issue or not

![image](https://user-images.githubusercontent.com/46523097/195427654-e5087729-0054-438b-bc3e-9124a2d1187f.png)

**Comment by Wall-core** [comment]
https://classicdb.ch/?object=73941#wh-comments

Can you confirm that this does not exist in classic? It may be a scrap from TBC left over.

**Comment by sudolink** [comment]
> https://classicdb.ch/?object=73941#wh-comments
> 
> Can you confirm that this does not exist in classic? It may be a scrap from TBC left over.

https://www.wowhead.com/classic/object=73941/ooze-covered-gold-vein
classic wowhead says they're only in feralas & thousand needles

But cannot confirm ingame, so closing.
