### ISSUE TITLE
Unknown Invisible mob hitting for huge dmg

### ISSUE THREAD

**Issue by ApathySilence** [Wall-core/Everlook-Bugtracker#283]
this hut in Duskwood, at The Rotting Orchard has an invisible mob that hits for 270 dmg 
![image](https://user-images.githubusercontent.com/115675774/195476777-4bef4212-8d0b-4892-8afd-0f4df1150e10.png)

**Comment by sudolink** [comment]
did you maybe use an aoe skill?
https://wowpedia.fandom.com/wiki/Unseen

**Comment by Xazamas** [comment]
Most likely you aggro'd an Unseen like sudolink suggested.

However, I've encountered at least one invisible mob, at the place where you're supposed to trigger Murkdeep spawn. I would've been killed if I hadn't been able to put Voidwalker on Defensive, making it fight the invisible mob(s).
![WoW_jprgJU2jC8](https://user-images.githubusercontent.com/115695553/195540254-90835914-e77d-4e01-9d4d-10b7ede478bd.png)

**Comment by Croissantlol** [comment]
Invisible Kobolt Miner for me too, impossible to complete the quest

**Comment by Croissantlol** [comment]
![bugmurkdeep](https://user-images.githubusercontent.com/113902654/195605339-29bf325e-7a40-4b86-9a90-744dd074e4ae.png)

**Comment by Wall-core** [comment]
> Invisible Kobolt Miner for me too, impossible to complete the quest

you are posting a different issue in an unrelated ticket; the issue you're posting about has been fixed

**Comment by Wall-core** [comment]
> did you maybe use an aoe skill? https://wowpedia.fandom.com/wiki/Unseen

this is correct
