### ISSUE TITLE
[Diremaul Tribute] Cho‘Rush [BUG question]

### ISSUE THREAD

**Issue by Sh1NoX08** [Wall-core/Everlook-Bugtracker#287]
[Since nobody have mentioned this issue on Bug-Tracker]

On the last Boss Fight in Tribute the NPC Cho‘Rush (Mage/Priest/Shaman) seems to regenerate Mana way too fast (~around 100% increased) therefore its impossible to OOM(out of Mana) him. 

Is this intended or a bug? Thanks in advance!

-sHiN

**Comment by Wall-core** [comment]
It's been adjusted already.
