### ISSUE TITLE
WANTED: Murkdeep! bugged?

### ISSUE THREAD

**Issue by levomir** [Wall-core/Everlook-Bugtracker#295]
I think the quest "WANTED: Murkdeep!" is bugged (an invisible mob killed me, it had sunder and root skills so it might have been the boss but I couldn't target)

**Comment by levomir** [comment]
This seems to happen when I go in the water right infront of the murloc camp where he suppose to spawn after certain amount of murloc kills.

**Comment by levomir** [comment]
Combat log is saying "Kobold Miner"

**Comment by levomir** [comment]
![xxx](https://user-images.githubusercontent.com/115743758/195711486-9fb5808f-92d8-4881-b343-84a292d749ce.png)

**Comment by Wall-core** [comment]
Read dev updates; it's fixed next patch and has been posted several times already. Search through bugtracker to ensure you aren't posting duplicate issues.
