### ISSUE TITLE
Broken items sells for full price

### ISSUE THREAD

**Issue by Alakoris** [Wall-core/Everlook-Bugtracker#299]
Looks like a fully broken items sells for a full price (while at vendor price shown as 1 copper)
![image](https://user-images.githubusercontent.com/115734023/195744422-723c5a76-9415-48be-a0cd-21c45897c1af.png)
![image](https://user-images.githubusercontent.com/115734023/195744463-27facfe3-c202-400d-9894-b14b684e8e0c.png)

**Comment by Gamemechanicwow** [comment]
Fix has been merged to vmangos.
