### ISSUE TITLE
Fungal Spores in the Barrens

### ISSUE THREAD

**Issue by Djanti** [Wall-core/Everlook-Bugtracker#307]
There are not enough fungal spores spawning. Not sure if the respawn timer is correct, but the quantity of the fungal spores are far, far too low. I see this issue has been stated multiple times already but it is not fixed and it is not working correctly.

**Comment by NickTyrer** [comment]
They can spawn at the three pools in the barrens, did you check those?

**Comment by FlagFlayer** [comment]
The quantity of fungal spores is low specifically in the Stagnant Oasis, where everyone picks them up, because they are all globally pooled together. The other 2 pools will have an overflowing amount of fungal spores. This is the intended behaviour for it.

**Comment by Djanti** [comment]
> 

I've been walking to and fro every pool and none of them seem to have an abundance of spawns. Took quite a while just to get the 4 necessary while usually it takes 1 trip to 1 pool. But perhaps this is normal on 1.4 patch?

**Comment by Djanti** [comment]
Anyhow, if it is normal for patch 1.4, then everyone is going to have an awful time getting the spores because there will be literally none left. People will be fighting for them lol. Feelsbadman. I know there will be dynamic respawns for mobs at first, but for quest items like this too?

**Comment by FlagFlayer** [comment]
If that's actually the case then there might be some issue with this. The intended respawn should be 3 minutes on every pickup, over a big swathe of possible spawn nodes. If you're using an addon (such as pfquest) for specific fungal spore locations you should know that there are more spread out spawn points that aren't displayed as the addon doesn't know of their existence.

**Comment by Djanti** [comment]
No Add-Ons used. I've seen them spawn in quite a large range of locations but the timer does not seem to be every 3 minutes. The most annoying this about this is the spawn density though. I've never experienced a vanilla WoW realm where the spawn of these were so thinly spread in combination with such a slow spawn timer.

**Comment by FlagFlayer** [comment]
Tested just now on the PTR. The respawn rate is exactly 3 minutes. Spawn density seems normal, seeing that in every single oasis I found at least 4 Laden Mushrooms (the object that contains Fungal Spores). When the area has a lot of people the density would probably prove quite low though, dynamic respawns need to be implemented for the object Laden Mushroom [3640].
