### ISSUE TITLE
horde side quests for WC

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#31]
Serpentbloom quest is currently acceptable WITHOUT completing Fungal Spores prequest chain.

this is a horde only Wailing Caverns chain quest much like raptor horns that requires completion of a prequest in order to accept it. (raptor horns is not horde only)

see pictures 

![serpentbloom prereq prequests to get this quest](https://user-images.githubusercontent.com/35550935/178126840-c35fefb7-efaf-4cb9-bc39-0e3ac765383b.png)

![serpentbloom prereq prequests to get this quest 02](https://user-images.githubusercontent.com/35550935/178126845-3a53b9ea-2458-45d2-9557-0a333eddfa5b.png)

**Comment by hgarner17** [comment]
Wall noted it may be due to the patch testing is being done in. patch 10

it was certainly NOT this way in earlier patches. (and either way it is a CHAIN quest.. so you should be required to start the CHAIN to get the final quest of the chain)

**Comment by Daribon** [comment]
There is no pre-quest for Serpentbloom on classic and wowhead (allakhazam) comment from patch 1.8.0 notes that neither was there any pre-quest for it back then.

You should be able to pick up Serpentbloom without completing any quests.
