### ISSUE TITLE
Coldridge Pass Lagged

### ISSUE THREAD

**Issue by ohmygoshoctopus** [Wall-core/Everlook-Bugtracker#311]
Coldridge Pass is extremely laggy; only once per second does any action take place. This is unrelated to the rest of the game (my other characters are working fine) or the server (I can log out and back in to the same symptoms, but only in that area). If you turn back towards Anvilmar, the lag stops. 

Also, oddly, if you click anywhere on any of the terrain, you target "Spotter Klemmy."

This is on the Coldridge Valley side of the tunnel.

**Comment by Roflkopterr** [comment]
I tested this with 4 other people. Confirmed. Seems to only happen in gnome/dwarf starter area. Started less than 24 hours ago.

**Comment by ohmygoshoctopus** [comment]
Tested again tonight and is working normally.
