### ISSUE TITLE
There is no Spirit healer at Raven hill (Duskwood)

### ISSUE THREAD

**Issue by Avelorian** [Wall-core/Everlook-Bugtracker#314]
Not much to say more.... There is no Spirit healer at Raven hill (Duskwood).

**Comment by FlagFlayer** [comment]
Raven hill graveyard was added in patch 1.8 progression wise. Server is currently on 1.4. On live all graveyards will be available regardless of progression.

**Comment by Daribon** [comment]
This will be fixed when https://github.com/vmangos/core/pull/1637 is merged. It is currently incorrectly set as graveyard when server is configured for pre patch 1.8.

**Comment by FlagFlayer** [comment]
This has been fixed in the latest PTR update.
