### ISSUE TITLE
NPC pathing

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#32]
in TB there is a guard that is walking over a street sign. It's not a big issue but just looks bad every time he walks around he steps 6 feet into the air (how tall are taurens?) 
I primarily play as alliance but made a tauren went to TB and noticed this in the first 20 seconds of being there. It's annoying
![pathing for npc off in TB](https://user-images.githubusercontent.com/35550935/178126923-48346e4d-f0bf-4c6f-a124-61b3ab4985b3.png)

**Comment by hgarner17** [comment]
the rest of the path around the circle seems fine.. just fine tuning needed

**Comment by Wall-core** [comment]
I'll redo the various maps when I move everything to the new equipment.
