### ISSUE TITLE
Air bubbles don't work

### ISSUE THREAD

**Issue by Djanti** [Wall-core/Everlook-Bugtracker#329]
When underwater, for example in the Stagnant Oasis in The Barrens, the air bubbles do not replenish the Breath bar.

On a slightly related note, holding Spacebar while underwater makes you jump and not surface.

**Comment by ronaldofenomeno** [comment]
i think the spacebar thing is normal in vanilla

**Comment by FlagFlayer** [comment]
The spacebar jump has been an issue with how water is currently coded in private servers, and has been an issue for years. The air bubbles in the Stagnant Oasis are not of the type that should replenish the breath bar. There are different, identical looking objects that do replenish the breath bar, for example the fissures at The Sludge Fen or in Silverpine Forest, used for the druid class quest Trial of the Sea Lion. Those fissures work correctly and this is all intended behaviour.

**Comment by Gamemechanicwow** [comment]
Jumping under water is blizzlike. It wasn't changed until tbc.

**Comment by FlagFlayer** [comment]
I heard differently from a friend, but apparently they were wrong: https://youtu.be/FaV6oAteJGI?t=2450
