### ISSUE TITLE
Stitches - Duskwood (chatlog messages)

### ISSUE THREAD

**Issue by Atlanbugreports** [Wall-core/Everlook-Bugtracker#332]
Stitches will occasionally output a white message in chatlog that isn't dialog and appears to be a visible script command that can be seen by in game character.

**Comment by Atlanbugreports** [comment]
bug was witnessed as stitches was moving by the rotting orchard toward the tranquil gardens cemetery.

**Comment by Wall-core** [comment]
Addon issue, likely related to Prat or Lazypig
