### ISSUE TITLE
Goggeroc - Stonetalon mountains (chain stun)

### ISSUE THREAD

**Issue by Atlanbugreports** [Wall-core/Everlook-Bugtracker#334]
Goggeroc appears to nearly chain stun alternating between his "snap kick" and "uppercut" abilities. 

while referencing https://www.wowhead.com/classic/npc=11920/goggeroc#comments

i was unable to find any accounts of him stunning back to back over and over. 

he stuns so fast that level appropriate shaman cannot cast healing wave and heal through it. Likely needs cooldown added to at least 1 of the stuns so he doesn't alternate and chain stun ever 3-4 seconds(or less).

**Comment by FlagFlayer** [comment]
"By [kokusho](https://www.wowhead.com/classic/user=kokusho) (1,075 – 1·17·12) [on 2007/02/28](https://www.wowhead.com/classic/npc=11920/goggeroc#comments:id=43571) (Patch 2.0.8)		
Goggeroc is a pretty tough earthen (he looks like a dwarf). He has a lot of HP and the only two notable abilities that I noticed were a knockback and Snap Kick which stuns. I soloed him at 23 as a mage and it was still pretty tough. If you do this quest at the appropriate level, definitely bring a party."

Considering this comment was made after mob nerfs that came from later vanilla patches, I believe it is intended to be this difficult. A level appropraite shaman shoul not be able to kill this mob alone: Remember that this is an elite quest intended for parties.

**Comment by Atlanbugreports** [comment]
I've never seen him this tough on other servers. Perhaps he was nerfed there. I solo'd him on lights hope and every other server while level appropriate. Just writing it off as you need a party doesn't address the fact that he chain stuns and no where on any database is he described as such. You must've kited him on the mage.

**Comment by Atlanbugreports** [comment]
I checked out videos of this fight from classic wow and the only difference appears to be that he doesn't alternate between stuns regularly but occasionally lands both stuns at once. 

Most of the videos of people soloing him are either a mage kiting or a pet class. 

He's a video of the a 24 warrior killing him(barely) with retaliation and you can he lands an snapkick during an uppercut which overlap at the same time and traps the player mid air. 

**https://youtu.be/n6k3dHowa1g?t=645**

He's definitely a nasty little bugger and is a huge undercon for a 20 elite. Will check him out again later tonight on PTR to see exactly how he fights here vs classic if I can.
