### ISSUE TITLE
Searing totem (reflective damage)

### ISSUE THREAD

**Issue by Atlanbugreports** [Wall-core/Everlook-Bugtracker#335]
Searing totem dies in 1 shot to a enemy npc humanoid with lightning shield up. I assume it also works with thorns. 

I do not ever recall a searing totem dying to reflective damage and do not think this is working as intended. 

Totems should be immune to magic reflective damage otherwise it dies every time somebody with thorns, lightning shield, or nagelring is struck by searing totem fireball.

**Comment by FlagFlayer** [comment]
The fireball that Searing totems use is a spell, and thus triggers Lightning Shield as per text: "When a spell, melee or ranged attack hits the caster, the attacker will be struck for X Nature damage." Intended behaviour for this.

Your assumptions on Thorns and Naglering are wrong: They only affect melee attacks, not spells. Both Thorns and the Thorns-like effect from Naglering are a Damage shield-type aura, meanwhile Lightning Shield is a Proc Trigger Spell-type aura, which has a different behaviour.
