### ISSUE TITLE
PVP bug (invalid target) 

### ISSUE THREAD

**Issue by Atlanbugreports** [Wall-core/Everlook-Bugtracker#338]
Server shut down for scheduled restart yesterday during level 30 PVP in Arathi Highlands. I was in combat during shutdown. 

Upon logging back into game I was unable to cast on anybody in PVP and received the message "invalid target" even though I attempted to attack/cast on several members of the opposing faction effectively leaving me a sitting duck upon relogging back in. Alt+f4ing and restarting client fixed the bug's behavior. 

Unable to test to confirm bug without server restart. Please note this was a scheduled restart with yellow server message and not a crash.

**Comment by Simp-N** [comment]
This typically happens if you alt-tab during the loading screen. The game seems to think you're still holding alt. Pressing alt again will fix it.
