### ISSUE TITLE
NPC "Huntess Leafrunner" in Darnassus at least double the size of the other patrolling huntresses.

### ISSUE THREAD

**Issue by snubbenn** [Wall-core/Everlook-Bugtracker#339]
Pic related.
![bug](https://user-images.githubusercontent.com/115948562/196052506-86a76f63-97b8-4a82-83d5-96fb5da02bad.png)

**Comment by snubbenn** [comment]
For reference:

![bug2](https://user-images.githubusercontent.com/115948562/196052672-fffcabfc-cb31-4ddc-b472-3c1e794f9f8e.png)

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1630
