### ISSUE TITLE
serpentbloom is not clickable 

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#34]
See images posted. *note Wall already has an update being worked on*

When doing Serpentbloom quest in WC the nodes outside (and several inside) are not easily clickable. (almost as if they are behind a rock or inside another invisible plant) 

there is certain corners of the flower that can be picked.

![cant click serpentbloom 04 all blooms](https://user-images.githubusercontent.com/35550935/178128715-7772c5a0-1e77-4573-9d34-96b6bcd4114a.png)

![cant click serpentbloom 05all blooms](https://user-images.githubusercontent.com/35550935/178128727-bb1c039c-7c1d-49f5-a321-fe1a36904b46.png)

![cant click serpentbloom 03 all blooms](https://user-images.githubusercontent.com/35550935/178128735-d5c7f3e6-6493-4139-856b-560e9607e55e.png)

![cant click serpentbloom 02 right entrance to cave](https://user-images.githubusercontent.com/35550935/178128740-56aa7323-819b-4605-8f6c-d3a13dcb38e5.png)

![cant click serpentbloom 01 right entrance to cave](https://user-images.githubusercontent.com/35550935/178128748-e566312a-f06e-4e59-b85f-31ca0d07c0a3.png)

**Comment by hgarner17** [comment]
"I'm confident they work" ... then it doesn't work

That's why we are testing things :'D

**Comment by NickTyrer** [comment]
The serpentbloom issue is a client bug (the client prioritises the trap rather than the lootable object). Although this cant be fixed in vmangos the server owner can make the trap invisible using ```UPDATE `gameobject_template` SET `displayId` = 0 WHERE `entry` = 19535;```

**Comment by Wall-core** [comment]
Added to Everlook migration
