### ISSUE TITLE
6-slot-pouches drop too often

### ISSUE THREAD

**Issue by eiermane** [Wall-core/Everlook-Bugtracker#341]
Hi im pretty sure that the drop rate of the early game 6-slot-bags is way too high.
Please check, I hope it wont be the same on the live server.
I remember some other server had the same "issue". Thanks.

**Comment by FlagFlayer** [comment]
This may be related to vmangos drop tables having many issues. The drop tables to be completely reworked, and I don't see a fix for this coming in the near future.

For all it's worth, I only got 2 bag drops in 15 levels before getting a bunch of 8-slot drops, but that is anecdotal, and I've seen a lot of people mentioning "too many bag drops" in world chat.

**Comment by FlagFlayer** [comment]
Related issue: https://github.com/Wall-core/Everlook-Bugtracker/issues/196
Possibly related drop tables issue: https://github.com/Wall-core/Everlook-Bugtracker/issues/286

**Comment by ohmygoshoctopus** [comment]
Also anecdotal, but I leveled a character to 10 and a second to 6 without seeing a single bag drop.

**Comment by Wall-core** [comment]
It's all random, you're just getting lucky.
