### ISSUE TITLE
"Invalid Target" Error on Multiple Mobs in STV

### ISSUE THREAD

**Issue by GGTV01234** [Wall-core/Everlook-Bugtracker#344]
I saw an "Invalid Target" error when trying to cast on these mobs in STV: Young Stranglethorn Tiger, Young Panther, River Crocolisk. After trying a few different mobs, the error stopped, and I had no issues killing the mobs.

**Comment by FlagFlayer** [comment]
What were you attempting to cast? Were you using any addons or macros? This could also be a WDB issue, so clearing that folder could help you stop that issue persisting.

**Comment by Simp-N** [comment]
Presumably the same as https://github.com/Wall-core/Everlook-Bugtracker/issues/338

This typically happens if you alt-tab during the loading screen. The game seems to think you're still holding alt. Pressing alt again will fix it.
