### ISSUE TITLE
You Can Jump into the Great Forge

### ISSUE THREAD

**Issue by ohmygoshoctopus** [Wall-core/Everlook-Bugtracker#345]
I haven't a clue if you could in vanilla, but you can jump to that wheel on the south side to get into the lava pit.

**Comment by Wall-core** [comment]
Yes this is intended and blizzlike. Be careful falling in while in ghost form as you'll need a GM to get you out lol

**Comment by Dusthoof-Qiraji** [comment]
No, it's not. Tick ​​damage at low speed. You can even fight in lava.
