### ISSUE TITLE
Shimmering Flats - race dialog

### ISSUE THREAD

**Issue by Atlanbugreports** [Wall-core/Everlook-Bugtracker#350]
![image](https://user-images.githubusercontent.com/115944878/196113761-66e9517e-b39c-4446-b663-d21817549da4.png)
fobeed the race announcers for shimmering flats has this white text output into chat log.

i also believe radixx should win every race, but that's just me. 

maybe add small human npc called "kid who hates sand" that says "now this is podracing'

**Comment by Wall-core** [comment]
Addon causing white text, likely Prat or Lazypig. Also kekw
