### ISSUE TITLE
Mok'rash -Stranglethorn vale ( Chat Script)

### ISSUE THREAD

**Issue by Atlanbugreports** [Wall-core/Everlook-Bugtracker#351]
![image](https://user-images.githubusercontent.com/115944878/196120969-ca69d5f4-0dc1-4420-8885-b0541a75db03.png)
Mok'rash in stv displaying white text commands in chat log.

**Comment by Wall-core** [comment]
That's an addon causing it, likely Prat or Lazypig

**Comment by Atlanbugreports** [comment]
I dont use lazypig so it must be prat causing these. Will head to booty bay and test today.

**Comment by Atlanbugreports** [comment]
![image](https://user-images.githubusercontent.com/115944878/196554715-433b3777-d155-4af9-89fa-4bdf3a37be82.png)
It still occurred without prat enabled. Disabling all addons and checking again.

**Comment by Atlanbugreports** [comment]
![image](https://user-images.githubusercontent.com/115944878/196677622-71a18c1b-9187-4a2b-bde5-83bcde201845.png)
appears to not happen with no addons enabled. trying to determine which addon is responsible
