### ISSUE TITLE
Frostbite is delayed about half to even 1.5 sec from landing frost spell

### ISSUE THREAD

**Issue by laytya** [Wall-core/Everlook-Bugtracker#356]
I think its not intended

**Comment by laytya** [comment]
https://imgur.com/a/ckZwqtI

![frostbite](https://user-images.githubusercontent.com/20452393/196328366-f96772d4-d659-4b01-a86d-77e3f2abd68f.JPG)

look at chronometer bars - almost 2.2 sec between land and proc frostbite.

**Comment by Wall-core** [comment]
the proc delay is 0.5 seconds, you are probably experiencing latency. This is purposely done to prevent spell crit batching from breaking its own frostbite.

**Comment by laytya** [comment]
I have 100ms Latency - but delay 1.5 -2 sec - mob can do 2-3 steps before stop
