### ISSUE TITLE
falling off zeppelin from Org to Grom'gol

### ISSUE THREAD

**Issue by arooks1** [Wall-core/Everlook-Bugtracker#357]
When taking the zeppelin from Orgrimmar to Grom'gol, after the loading screen, I'm getting thrown off into the water. Was standing on the top (main) deck
![WoWScrnShot_101722_195149](https://user-images.githubusercontent.com/115400565/196247892-2793477f-3dd5-405a-a830-064964df793c.jpg)

**Comment by arooks1** [comment]
I attempted to recreate this today, took the same zeppelin about 12 times while standing in all different places, but everything was fine today. Not sure how/why I got thrown off twice yesterday.

**Comment by Wall-core** [comment]
Likely due to anticheat
