### ISSUE TITLE
Release spirit bouncing back and forth registers as cheating/teleporting

### ISSUE THREAD

**Issue by astroglaid** [Wall-core/Everlook-Bugtracker#362]
When "Releasing Spirit" in a battleground, your ghost will sometimes be bounced from the graveyard back to your corpse before returning to the graveyard. Everlook apparently seems to register this rapid hopping of your ghost as teleporting and awards an auto-ban.

**Comment by Wall-core** [comment]
The anticheat will be adjusted today to prevent this
