### ISSUE TITLE
Player portrait bug

### ISSUE THREAD

**Issue by ronaldofenomeno** [Wall-core/Everlook-Bugtracker#364]
the player portrait does not disappear when i move far away from the player. image pasted in this report. im near the bank while i clicked on the player on the stormwind gate. and the portrait is still there.

Also, the buff he has is shown i little far away from its spot directly under the portrait

![image](https://user-images.githubusercontent.com/33092150/196303998-4794704a-2a87-4e95-8c85-adc1077bbef5.png)

**Comment by Wall-core** [comment]
It's due to render distances being maxed on PTR

**Comment by ronaldofenomeno** [comment]
Also, what about the buff icon of the player under his portrait? its place doesnt seem right. any solutions?

**Comment by NickTyrer** [comment]
Nope, thats how the 1.12 client works.
