### ISSUE TITLE
Fatigue bar while on zepplin?

### ISSUE THREAD

**Issue by FlagFlayer** [Wall-core/Everlook-Bugtracker#372]
While taking the zepplin from Undercity to Orgrimmar I noticed a weird bug where a fatigue bar appeared once I loaded in to Durotar. The fatigue bar continued draining, and would've probably killed me for fatigue. However, moving on the boat made the game realise I was not in a fatigue zone and filled the bar back up. I have tried multiple times to replicate this bug, but have not been able to.

**Comment by ghost** [comment]
This was a known issue even on retail wow back in the day. 
I have not yet have it happen to me.

**Comment by FlagFlayer** [comment]
In all my time playing vanilla this was the first time I had this, which is interesting I suppose.

**Comment by FlagFlayer** [comment]
Since this was retail wow behaviour, I suppose it doesn't need any fixing.

**Comment by Wall-core** [comment]
This is likely due to anticheat; If you were using 1.14 client, it would explain it. But even on 1.12 client, the anticheat sometimes thinks you're not on a valid transport and rejects packets showing you on transport so you don't receive the standard fatigue immunity

**Comment by FlagFlayer** [comment]
I was using the 1.12 client, just some anticheat behaving how it's supposed to with a blizz-like bug
