### ISSUE TITLE
Earthbind Totem breaking Rogue Stealth + Slow Debuff Lasting Long After Totem Is Destroyed

### ISSUE THREAD

**Issue by PoeEverlook** [Wall-core/Everlook-Bugtracker#375]
Right now Earthbind Totem is breaking Rogue Stealth and the Totem's Slowing Debuff is Lasting Long After Totem Is Destroyed. 

This is pretty game breaking in PvP and is not Vanilla-like.

**Comment by ghost** [comment]
Earthbind did not stop breaking Rogue stealth until Patch 2.2.0 in Sept 2007; 8 months after TBC launched, in 2006 it did break stealth, therefore it is vanilla like.

for source http://www.wowwiki.com/Patch_2.2.0

**Comment by kalypto89** [comment]
any shaman totem with aoe effect should break stealths
