### ISSUE TITLE
Remorseless Attacks don't work

### ISSUE THREAD

**Issue by Lorecomeone** [Wall-core/Everlook-Bugtracker#377]
It seems the talent Remorseless Attacks, I tried it on almost 200 mobs and the crit chance was around 5% that is my standard character critc chance. Maybe it is just RNG but it is very strange to crit 5% of the time with a 45% crit chance.

**Comment by Simp-N** [comment]
Tried this but the crit chance seemed fine for me. Out of 50 Sinister Strikes with Remorseless Attacks up 29 critted, two missed, one parried and the rest were hits.
Base crit chance is 14.2%, and with Remorseless that'd be 54.2%.
**29 / 50 = 58%**
This was on a lvl 30 rogue, attacking lvl 27-28 mobs, starting with 141 sword skill going up to 150.
