### ISSUE TITLE
Gadgetzan Guards

### ISSUE THREAD

**Issue by nicole-woebse** [Wall-core/Everlook-Bugtracker#379]
The Gadgetzan Guards (maybe other neutral Guards as well) attack you when an enemy player is attack you, even when you dont do anything and dont have buffs like thorns.

**Comment by ghost** [comment]
If I remember correctly I spent a lot of time in Tanaris and so long that you didn't do any damage when attacked; the guard's would not go after you and remained yellow named neutral,  I believe that this is correct.
