### ISSUE TITLE
Can't pull the mobs out of tent - Tanaris coords (63,30)

### ISSUE THREAD

**Issue by WE1ZARD** [Wall-core/Everlook-Bugtracker#389]
Can't pull the mobs out of tent - Tanaris coords (63,30)
the only way to kill this mob is to get in that tent,
it's so annoying since im caster.
![Tanaris coords (63,30)](https://user-images.githubusercontent.com/111175406/197109310-5b791b16-bbba-4338-86d5-c6eefaaefabc.png)

**Comment by ohmygoshoctopus** [comment]
I've had this on other servers and in official Classic. I think it's just that way. Which, yes, is awful as a caster.
