### ISSUE TITLE
Coldridge Pass Lagged

### ISSUE THREAD

**Issue by wonderlandx** [Wall-core/Everlook-Bugtracker#390]
Drops to approximately 0.5 FPS, followed by a disconnect or crash if you keep running from the starting zone towards the pass. Not my PC, happens to everyone. 

Same thing happened last week, fixed itself, and its broken again now.
#311

/e server stopped lagging but the underlying issue is probably not fixed.

/e fixed, closing

**Comment by yesilmen-vm** [comment]
Can confirm the issue still exists.
