### ISSUE TITLE
Dueling Deaths

### ISSUE THREAD

**Issue by jrdnrholt** [Wall-core/Everlook-Bugtracker#394]
Was dueling last night and maybe 1 out of 10 or so resulted in the losing duelist dying and having to corpsewalk back to body.

**Comment by bathsalts666** [comment]
same. deaths occur more often when i cast an instant cast spell after a cast (i.e frostbolt then fireblast, lightning bolt then earth shock) when the instant cast spell is the killing blow its been more often than not i die.

**Comment by Wall-core** [comment]
It's due to batching.
