### ISSUE TITLE
please fix wsg warlock pet respawn

### ISSUE THREAD

**Issue by kalypto89** [Wall-core/Everlook-Bugtracker#398]
currently if your pet died, and then you died - the pet will not revive upon ress. this is very taxing on shards. please fix

**Comment by wonderlandx** [comment]
This is Vanilla like. Classic auto respawned the pet but thats not how the original game was.

**Comment by kalypto89** [comment]
pet needs to rezz with you. wasting a shard+mana+time on the ressurect in warsong gulch for example is just griefing, its not even vanilla like

**Comment by Wall-core** [comment]
this is blizzlike vanilla.

**Comment by kalypto89** [comment]
thats not really balanced; imagine having to summon your pet every time you died in WSG/AB when ranking. Having to spend 10 seconds to summon pet and over 1k mana and also a shard on release in pvp environment. I understand the fantasy/roleyplaying/pve aspect of it and im fine.. but in a player vs player environment its just a handicap. I really think you should change warlocks and hunters to be able to have their pets ressurected after death in pvp instanced areas.. open world is one thing but battlegrounds is different... why not take the actual good improvements that classic brought and implement them in your server instead of being stiff about "that's what vanilla was like 20 years ago"

**Comment by KevinTyrrell** [comment]
> thats not really balanced; imagine .....

**Wall of Text hits you for 4795 Shadow Damage (Critical)**

**Comment by wonderlandx** [comment]
It is actually balanced bc warlocks are buff as hell and need to be punished for deaths. Premades felt awful when you kill the warlock on ramp then hes back with full mana and pet by time you've reached the flag. 

It was a bug in Classic from changes in later expac, not an improvement.

**Comment by kalypto89** [comment]
> It is actually balanced bc warlocks are buff as hell and need to be punished for deaths. Premades felt awful when you kill the warlock on ramp then hes back with full mana and pet by time you've reached the flag.
> 
> It was a bug in Classic from changes in later expac, not an improvement.

Your logic is so flawed I don't know where to even start.
