### ISSUE TITLE
Lunar fungus ought to spawn 1-3 fungi

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#40]
The druid poison quest calls for gathering of 12 lunar fungus.  on a fresh server launch this will be very difficult for more than one druid to complete at a time. and if two are attempting the same quest at the same time there WILL NOT be enough lunar fungus for them both.  (i think the total number of spawns that i am aware of is about 18 ish

I have seen this remedied by having each spawning node generate between 1-3 fungi each time the node is looted. 
(not sure if i saw this in Classic or in SoM or on Pserver but it was a very effective method to completing the quest when competition is in the area.)

![lunar fungus druid poisons quest](https://user-images.githubusercontent.com/35550935/178168920-b541db0e-1b56-4035-9068-c471c0d571cb.png)

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1483

**Comment by hgarner17** [comment]
Oh nice. so that means they'll address this issue in Vmangos right?
