### ISSUE TITLE
Charge Combat Trigger

### ISSUE THREAD

**Issue by Iskato** [Wall-core/Everlook-Bugtracker#401]
Expected behavior: Charge should put you in combat on cast
Classic: https://youtu.be/Kh4WGkPe0b0?t=3
Vanilla: https://youtu.be/yy4vdS_ocmg?t=130
Actual behavior: Charge does not put you in combat at all (which leads to the fact that you dont start combat with the amount of rage that charge gives you on cast)
https://imgur.com/a/F3jn6a6

**Comment by Wall-core** [comment]
You're using it on a neutral mob, that's why.
