### ISSUE TITLE
trial of the sea lion underwater breath areas

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#41]
Normally i will use teleport to moonglade after i get the pendant off the shores of westfall.

but! 

I have seen servers with a clam shell down by the box that gives air so that you don't drown if you make it all the way down.

I have also seen it where when you open the box a bubble of air pops out and it replenishes your breath. (it hovers in the area near the box) 
for players who do not want to turn in that quest just yet and do not wish to drown (as you are pretty far down and won't make it back up before dying) place a clam shell breather next to the box.

![trial of the sea lion 03 breathing b](https://user-images.githubusercontent.com/35550935/178169153-7466ca27-4732-4e56-8363-f76a35c5043b.png)

**Comment by hgarner17** [comment]
Note: I did NOT see the elite shark swimming by. check to ensure there is one that pats. not sure if there is or not.

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/commit/b8ccb0397686e41d1c3ea2cb7214425cd998e7a4
