### ISSUE TITLE
Alchemy supplies vendors still do not have health/mana potions for sale

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#416]
I have reported this before. there are alch supply vendors in every major city that are supposed to carry 2-3 lvl 3 healing potions and the low level mana potion 1-2 

These are not every at their respective vendors yet there are random vendors all across the world that DO sell the potions. This is not like Classic or SoM. On any dead server you could run to and buy the potions from vendors.

![5 13](https://user-images.githubusercontent.com/35550935/197376780-17a672ab-8ff8-4866-8ba0-7af909ae866c.png)
This is a sample vendor from a lvl 20-30 questing zone. the alchemy shop is lvl 3 health potions and lvl 5 mana pots

**Comment by hgarner17** [comment]
![bug alchemy vendor still does not sell min lvl 3 health pots and lowbie mana pots](https://user-images.githubusercontent.com/35550935/197376825-f2bdc534-89e1-49de-9977-5585a5352c76.png)
This is the specific vendor that SHOULD but does NOT have alchemy potions in limited supply.

**Comment by NickTyrer** [comment]
He doesnt sell those potions.
