### ISSUE TITLE
Herbalism vendor in Darnassus does not have herb bag to sell

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#418]
Maybe it's because of patch 1.2 that we are on but there is no herbalism bag for sale (9 silver with rep 10 silver with out) at the vendor

![BUG IN OPEN PTR 02](https://user-images.githubusercontent.com/35550935/197376946-31b5276b-7897-4c63-8150-9b2de87140df.png)

**Comment by NickTyrer** [comment]
Its added in a later patch.
