### ISSUE TITLE
Pendant of the sea lion druid quest the earth does not rumble

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#42]
One of the cool effects of crafting the Pendant's two halves is that you are at the shrine and the screen starts shaking and the earth rumbles. (it's very cool)

Just one of those things that makes the game special but it is missing from both the first part (the under water bauble) and 2nd part (connecting the two pendants)

Maybe only the 2nd quest is supposed to rumble (that i cannot recal) but I know that at least one of these channeled events makes the ground shake and rumble.

![druid trial of the sealion 01 scene does not shake](https://user-images.githubusercontent.com/35550935/178169440-82920e1a-010c-4e6e-96d6-dd6d0932b3dc.png)

also the dryad cheers (didnt check to see if that was happening or not)

![druid tx pendant of the Sea lion 02](https://user-images.githubusercontent.com/35550935/178169471-9acab255-c28b-48fe-98f7-4a2086bd8e8e.png)

**Comment by hgarner17** [comment]
the dryad to the right where you turn in the quest is supposed to cheer. I didn't notice if she did or not.

**Comment by NickTyrer** [comment]
> the dryad to the right where you turn in the quest is supposed to cheer. I didn't notice if she did or not.

Closed in https://github.com/vmangos/core/commit/b8ccb0397686e41d1c3ea2cb7214425cd998e7a4
