### ISSUE TITLE
Halloween Event is gone since 22nd.

### ISSUE THREAD

**Issue by wonderlandx** [Wall-core/Everlook-Bugtracker#424]
I don't know if this is an issue or just PTR stuff. 

On Darrowshire the events were also expiring before they were supposed to (also it missed most events because they weren't put in during early patches because of progression and they weren't put in late patches because of faster timeline, so don't do progressive events it makes no sense).

**Comment by ghost** [comment]
they were removed temporarily as they caused an issue.
