### ISSUE TITLE
Test of Faith Quest

### ISSUE THREAD

**Issue by ghost** [Wall-core/Everlook-Bugtracker#429]
Leap of faith quest near the shaman air totem quest line
When you jump, you fall to your death instead of being teleported back to the cave. 
quite funny tho. 

Not sure if this is a known issue but wanted to post to ensure it was noted.

**Comment by FlagFlayer** [comment]
I've heard of this issue before, where if you didn't jump off of the edge of the platform but rather just walked off you would not be teleported. It's a vmangos issue.
