### ISSUE TITLE
Rogue quests poinsons 01 mini map quest icon not showing up

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#43]
when Agent Kiernen is invisible to the player, she is also invisible as a quest gold dot on the mini-map.  
minimap gold dot should still be visible even if the NPC is not (so you can actually FIND the quest turn in location)

quest is difficult enough for any new aspiring alliance rogue
![rogue quest poisons 01](https://user-images.githubusercontent.com/35550935/178852125-8cf9c144-d4c1-4b81-9a49-dc52b9433e30.png)

**Comment by ratkosrb** [comment]
That's not how this dot works. The client shows the dot if a creature which is currently visible has a quest that can be turned in. If the client does not know about the creature because you are too far to detect it, there is no way to show the dot.
