### ISSUE TITLE
Earthbind totem triggers unstealth

### ISSUE THREAD

**Issue by Acrylix73** [Wall-core/Everlook-Bugtracker#431]
When dueling a rogue and using earthbind totem it prompts the rogue out of stealth

**Comment by Daribon** [comment]
This is the correct behavior in vanilla.

**Comment by hgarner17** [comment]
No it most certainly is NOT the right behavior. earthbind SLOWS the target it is not a hunter's flair to remove stealth off a player that did not remove it themselves. It is a bug

**Comment by Daribon** [comment]
See the other two closed issues regarding the exact same thing:
https://github.com/Wall-core/Everlook-Bugtracker/issues/427
https://github.com/Wall-core/Everlook-Bugtracker/issues/375

> [[Earthbind Totem]](https://wowpedia.fandom.com/wiki/Earthbind_Totem): This totem will no longer break Rogue stealth.
https://wowpedia.fandom.com/wiki/Patch_2.2.0

> Earthbind did not stop breaking Rogue stealth until Patch 2.2.0 in Sept 2007; 8 months after TBC launched, in 2006 it did break stealth, therefore it is vanilla like.
