### ISSUE TITLE
Unable to mount in UC elevators

### ISSUE THREAD

**Issue by ghost** [Wall-core/Everlook-Bugtracker#432]
You cannot be mounted inside the undercity elevators, this was not accurate 16 years ago as you could be mounted the whole time in UC.

**Comment by FlagFlayer** [comment]
Proof from vanilla: https://youtu.be/gN3Z2vVNQAE?t=1792

**Comment by NickTyrer** [comment]
@Wall-core are you still using the old low res mmaps?

**Comment by Gamemechanicwow** [comment]
> @Wall-core are you still using the old low res mmaps?

This is unrelated to mmaps. Its part of void Player::DismountCheck() - Seems like UC elevator is the exception. 

Note: Joanas 1-60 videos are from 1.10 iirc

**Comment by ghost** [comment]
I have only played WoW in vanilla, I remember distinctively that players had their mounts in the elevators of UC activated.

**Comment by Gamemechanicwow** [comment]
> I have only played WoW in vanilla, I remember distinctively that players had their mounts in the elevators of UC activated.

when I wrote exception I should have been more specific. You can't mount on boats and zeppelins - and the implemented code targets all transports. From looking at the video, it should work. But I would like to dive deep and see if it changed at any point during Vanilla - or if there are other transports falsely affected.

https://github.com/vmangos/core/blob/bdc363a6f8cd31738461f7e166e2c98ad36d0907/src/game/Spells/Spell.cpp#L6975

**Comment by Daribon** [comment]
This has been resolved with this commit:
https://github.com/vmangos/core/commit/37bc993863962faf3a8261231ea104f7207fe2a7
