### ISSUE TITLE
Hunter Pets constantly switching to Passive mode in instance

### ISSUE THREAD

**Issue by Tessablanc** [Wall-core/Everlook-Bugtracker#434]
In a group doing RFD, my cat kept switching to Passive mode over and over. I tried setting him on both Defensive and Aggressive, and every time he just switched back to Passive. It was not clear what was triggering this. It didn't seem to happen when combat ended, but rather at random times.

**Comment by Wall-core** [comment]
Sounds like an addon or keybind issue.

**Comment by Tessablanc** [comment]
It's not a keybind, I checked. Really hope I won't be seeing this one again on live, because I'm not using any addon that would logically cause this.

**Comment by Tessablanc** [comment]
Also, if it really was an addon issue, I would have seen it happening repeatedly. But the only time I saw it was when I was in RFD, and it happened over and over. All the time I was soloing it never happened at all. It's some kind of bug.
