### ISSUE TITLE
Not able to mount on Ratchet boat.

### ISSUE THREAD

**Issue by Koscius** [Wall-core/Everlook-Bugtracker#441]
![image](https://user-images.githubusercontent.com/116603673/197901484-a4108208-d7ed-4651-9e64-bd0a77dd8bd7.png)

**Comment by Koscius** [comment]
Also not able to mount inside of Booty Bay, as it claims "you must be outside"

**Comment by Gamemechanicwow** [comment]
Not being able to mount on transports and in Booty Bay is blizzlike.

**Comment by FlagFlayer** [comment]
The only spot you could mount on was that one crate on the top deck, no idea if that works in vmangos though.

**Comment by Gamemechanicwow** [comment]
> The only spot you could mount on was that one crate on the top deck, no idea if that works in vmangos though.

It was fixed earlier today in Vmangos
![image](https://user-images.githubusercontent.com/2223066/198152545-4174dd46-1666-4da4-af0a-3b8d3c542abd.png)
