### ISSUE TITLE
Rogue Poison quest 03 mobs wrong loot table

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#45]
battered junkbox should only drop from the act of pick pocketing. it is not something any class other than rogue should be able to farm.  i killed the defias tower patroler and it dropped as part of it's loot table. this is not right.

i did not pick pocket this mob and a junk box dropped for me. the lock picking boxes should only be something that ROGUES can get via a class specific ability "pickpocket" 

![rogue quest poisons 03 wrong loot table](https://user-images.githubusercontent.com/35550935/178854639-04f94514-8589-439a-8e86-d244ad8e8381.png)

**Comment by Simp-N** [comment]
According to two comments on the [unit's Wowhead page](https://classic.wowhead.com/npc=7052/defias-tower-patroller), they should not be lootable when killed at all. 

The loottable (when killed) on vmangos and the pickpocket-table on the Wowhead page are very similiar, as if someone has mistakenly put the pickpocket loot as the drop loot.

**Comment by Wall-core** [comment]
Issue fixed in new vmangos commit
