### ISSUE TITLE
The Lost Caravan and Kurzen's Mystery Quests, long spawntime

### ISSUE THREAD

**Issue by Tobbetobster** [Wall-core/Everlook-Bugtracker#450]
Quested some with  a duo and noticed that the chest you need to click for "The Lost Caravan" quest in Swamp of Sorrows had a respawn time of 25-30 min. Similar issue on the "Kurzen's Mystery" quest in STV, might be the same for other quests where you have to click something. Made it hard to quest with a duo, now imagine if more players tried to do these types of quests. Is 25 min a normal respawn timer?

**Comment by ghost** [comment]
yes, usually escort quests take awhile to reset due to their difficulty, I remember this happening in vanilla and we would end up not doing it if failed due to the respawn time.

**Comment by Tobbetobster** [comment]
> yes, usually escort quests take awhile to reset due to their difficulty, I remember this happening in vanilla and we would end up not doing it if failed due to the respawn time.

Not talking about an escort, for "The Lost Caravan" you have to go click a chest to obtain "Wizard's Reagents", the clickable chest will then despawn for 25-30 min. https://www.wowhead.com/classic/quest=1421/the-lost-caravan

Kurzen's Mystery involves clicking 4 tablets around the trolls in STV, the tablets will despawn when one player clicks it and seem to also have a 25-30 min respawn timer. https://www.wowhead.com/classic/quest=207/kurzens-mystery

Maybe it's normal for private servers to have these long respawns but at least in classic the items respawned within a couple seconds. Just not sure if it's intentional or not as it's a pain in the ass to do these quests when leveling with a friend, and probably even worse when servers launch and are active.

**Comment by Gamemechanicwow** [comment]
Vmangos respawn times for these are 10 mins for the chest and 1 to 5 mins for the tablets.

**Comment by FlagFlayer** [comment]
Should be adjusted to be dynamic probably
