### ISSUE TITLE
I have lost connection but mb still in the game

### ISSUE THREAD

**Issue by AzioNik** [Wall-core/Everlook-Bugtracker#457]
Just watch the video: https://drive.google.com/file/d/1pZPs1bIHrVdyuUVpUztcD2z4rrPI5-QF/view?usp=sharing

First time I was buying some things from vendor, and see all around just walking like - server drop, but after relog all things was in my bag, I can interract but cant see it, also I cant strafe left or right, camera just drops in center like you can see in the video, and, I ask people around me after relog, they say "Dont have any problem wuth connection".

**Comment by AzioNik** [comment]
After afk 15 min, game didnt drop me, im still on the server I think

**Comment by AzioNik** [comment]
dont have this problems before massive disconects in PTR 26.10.2022

**Comment by Wall-core** [comment]
Server probably experienced a crash and client didn't disconnect. It's a rare bug that happens in these extreme circumstances.
