### ISSUE TITLE
GY skip bug

### ISSUE THREAD

**Issue by SirGorog** [Wall-core/Everlook-Bugtracker#459]
Died at Western Plaguelands near the Bulwark, respawned at the Bulwark GY as a Ghost, ghostwalked to Eastern Plaguelands and talked to the Spirit Healer at Darrowshire GY to respawn. But i DC'ed, logged back in and spawned at the Bulkwark GY again.

**Comment by FlagFlayer** [comment]
"Until some time in 2010, logging out and back in while a ghost would remove the restriction tying the character to the Spirit Healer nearest to its death. Thus, it was possible for a character to die in one zone, reach a Spirit Healer far away, relog, and resurrect safely at that Spirit Healer. The minimap arrow for the nearest Spirit Healer would also disappear." https://wowpedia.fandom.com/wiki/Spirit_Healer

**Comment by SirGorog** [comment]
> "Until some time in 2010, logging out and back in while a ghost would remove the restriction tying the character to the Spirit Healer nearest to its death. Thus, it was possible for a character to die in one zone, reach a Spirit Healer far away, relog, and resurrect safely at that Spirit Healer. The minimap arrow for the nearest Spirit Healer would also disappear." https://wowpedia.fandom.com/wiki/Spirit_Healer

I tried this today but with the same problem. And there is no minimap arrow for the nearest Spirit Healer.
First Run, i logged out at the Darrowshire GY Spirit Healer. This time i had no DC but spawned again at the Bulwark.
Second Run, i logged out at the start of Eastern Plaguelands. Again no DC but spawned ar the Bulwark.

So if multiple People Corpse camp you at your Corspe and at the Spirit Healer you can probably log out for some mins/hours.

**Comment by FlagFlayer** [comment]
This can be reported at https://github.com/vmangos/core/issues. This can probably be implemented.

**Comment by Wall-core** [comment]
I'll change this for the project to allow you to rez at any graveyard. Nelfs rejoice.

**Comment by SirGorog** [comment]
Still not working
