### ISSUE TITLE
Darkshore Auberdin Innkeeper unable to set HS to

### ISSUE THREAD

**Issue by r0mivk** [Wall-core/Everlook-Bugtracker#460]
^

**Comment by Xazamas** [comment]
Can not reproduce, I get message that Auberdine is my home and Hearthstone tooltip says it will return me there.

**Comment by r0mivk** [comment]
It's working for me too now, I did it three times before, there was no "blue dust" animation and my HS was still in Wetlands. Thanks for fixing it fast.
