### ISSUE TITLE
Blood of Heroes in EPL does not spawn elites

### ISSUE THREAD

**Issue by arooks1** [Wall-core/Everlook-Bugtracker#462]
When picking up Blood of Heroes in Eastern Plaguelands there should be two elites spawning. I tried picking it up and no spawns.
![WoWScrnShot_102822_131015](https://user-images.githubusercontent.com/115400565/198574187-4b723925-b3d5-446b-9aaa-05362d577a0a.jpg)

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1631
