### ISSUE TITLE
Warlock Pet Dismiss on summon

### ISSUE THREAD

**Issue by themrbluestar** [Wall-core/Everlook-Bugtracker#464]
Warlock pets are currently instantly dismissed when starting the summon of a different pet. They should be stunned during the cast so that if you cancel the current summon you don't lose your pet.

**Comment by Daribon** [comment]
Current behavior is correct.
Warlock pets did not get stunned in vanilla when you summoned a new pet.

https://www.wowhead.com/tbc/spell=32752/
The spell for warlock pet stun was added in TBC, it did not exist in vanilla.
