### ISSUE TITLE
Please let Devilsaur walk through 1ft water/swim.

### ISSUE THREAD

**Issue by wonderlandx** [Wall-core/Everlook-Bugtracker#465]
Their pathing goes through the water, but when aggro'd they can't walk through the same water.
![image](https://user-images.githubusercontent.com/111853165/198752040-5115547c-b5d1-4721-9616-3fd6538c921b.png)
If you attack them while they are crossing they bug out.

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1630
