### ISSUE TITLE
Casters can cast spells/detect stealths when they are not facing them.

### ISSUE THREAD

**Issue by Gullediv** [Wall-core/Everlook-Bugtracker#469]
Casters seems able to cast spells like shadowbolt, frostbolt ( or any spell that requries you to face the target) without facing them, when the target is behind them and close enough

![imagen](https://user-images.githubusercontent.com/116978140/198851018-f9311716-b618-48e1-849d-a63fea73a42d.png)

**Comment by Gamemechanicwow** [comment]
There is 1.4y zone around the caster where there is no orientation check.

I am not sure if this originated from researched blizzlike behavior or if it was added as a countermeasure to latency issues in PVP.

https://github.com/vmangos/core/blob/7862c8de30f6823c5b487c3f493d750123928ff1/src/game/Objects/UnitDefines.h#L58

**Comment by Daribon** [comment]
It is blizzlike.

It is listed on blizzs classic not a bug list:
> Standing on top of other players while facing away allows spells and attacks to be used.

**Comment by Gamemechanicwow** [comment]
> It is blizzlike.
> 
> It is listed on blizzs classic not a bug list:
> 
> > Standing on top of other players while facing away allows spells and attacks to be used.

Thanks for the info. I forgot all about that list :>
