### ISSUE TITLE
Question: is this tool tip wrong? Rogue Poison quest follow up Zanzil

### ISSUE THREAD

**Issue by hgarner17** [Wall-core/Everlook-Bugtracker#47]
just saw the tool tip seems to be in foreign language. maybe not

quest works
![Rogue poisons quest 08 gathering the items to cleanse 7 day poison](https://user-images.githubusercontent.com/35550935/178861436-8774356c-f8d7-4ea3-ae8d-250dc4c7be8c.png)

![Rogue poisons quest 09 is tool tip description in a foreign language](https://user-images.githubusercontent.com/35550935/178861458-ed77ec73-938f-4430-aa82-ea8c4284f24e.png)

**Comment by ratkosrb** [comment]
The name is the same in Classic, so it's not a bug.
https://classic.wowhead.com/item=8432

And it was the same back in 2005.
https://web.archive.org/web/20050331000301/http://wow.allakhazam.com:80/db/item.html?witem=8432
