### ISSUE TITLE
LoS issue: Maleki the Pallid

### ISSUE THREAD

**Issue by Tessablanc** [Wall-core/Everlook-Bugtracker#477]
Warrior pulled Maleki with his bow and then ran around a corner, out of Maleki's LoS. Maleki ran after the warrior until the warrior was out of LoS, at which point he stopped in place and did nothing. He didn't start moving again until a hunter moved into LoS and shot Maleki with their bow. Basically he seems to "forget" his target when it moves out of LoS.

**Comment by Wall-core** [comment]
It's just mapping issues in 1.12 client map generation. Won't be fixed any time soon, if it should even be fixed. Maybe he should switch to melee sooner if target is not in LoS, but i'd have to see his behavior on classic.
