### ISSUE TITLE
Aggro range

### ISSUE THREAD

**Issue by Dusthoof-Qiraji** [Wall-core/Everlook-Bugtracker#478]
As I have noticed many times, the aggro range of mobs is very small. This is especially noticeable in copies. You can safely walk, for example, in the brd around the ring of law past aggressive spectators as 60. It's not funny.

**Comment by Wall-core** [comment]
That is correct aggro range from vanilla; You are referencing old private server aggro range which was incorrect. We use the vanilla values for those mobs.
