### ISSUE TITLE
Armor Potion and Armor Scroll consumes do not stack.

### ISSUE THREAD

**Issue by jensbond420** [Wall-core/Everlook-Bugtracker#480]
![stacking](https://user-images.githubusercontent.com/117006350/198870799-6e4ba74c-6a80-4205-97c6-dbb4be76473c.png)
This is me on a level 10 Undead Priest and I cannot stack Scroll of Protection [item=3013](https://classicdb.ch/?item=3013) and Elixir of Minor Defense [item=5997](https://classicdb.ch/?item=5997)

Here is the vod of Light's Hope Core Northdale of Sceto stacking all 3 Armor Buffs https://youtu.be/NqhDZgAQwxI?t=573 
![stacking1](https://user-images.githubusercontent.com/117006350/198871064-eeef527f-383f-493d-a1aa-695b936a58d4.png)

They should stack If this server intends to follow the spirit of Light's Hope Core

**Comment by Wall-core** [comment]
Not blizzlike but i'll readd
