### ISSUE TITLE
tinkerer-gizlock

### ISSUE THREAD

**Issue by Chattex** [Wall-core/Everlook-Bugtracker#49]
tinkerer-gizlock (https://classic.wowhead.com/npc=13601/tinkerer-gizlock#abilities;mode:normal) 
should not be able to cast [goblin dragon gun](https://classic.wowhead.com/spell=13183/goblin-dragon-gun) while moving, it's a channeled spell.

**Comment by Wall-core** [comment]
Patch issue, it changes later.
