### ISSUE TITLE
[Mage: Insignia] didn't dispels slowing effect - Dazed

### ISSUE THREAD

**Issue by WE1ZARD** [Wall-core/Everlook-Bugtracker#491]
**[Mage: Insignia]** didn't dispels slowing effect - Dazed
- **Dazed**: Movement speed reduced by 50%, duration 4 secs.
- **Mage: Insignia**: Dispels all Fear, Polymorph and Slowing effects.

![1](https://user-images.githubusercontent.com/111175406/199052635-b5a16522-aa82-49f0-be57-04bdea0a8921.png)
![2](https://user-images.githubusercontent.com/111175406/199052646-c4688036-37b0-47f5-92fe-7663f157e3c2.png)

**Comment by Tessablanc** [comment]
Daze is a special debuff designed to prevent skipping content, and it cannot be dispelled by anything.

**Comment by WE1ZARD** [comment]
> 

kk, got it
