### ISSUE TITLE
Dreadsteed not summoning

### ISSUE THREAD

**Issue by AidanDarlington** [Wall-core/Everlook-Bugtracker#495]
Dreadsteed corner buff icon shows, but the mount nor the speed actually activates
![image_2022-11-01_124139086](https://user-images.githubusercontent.com/90875034/199129360-8899283f-16f6-4795-b6c4-f7bef6708ac8.png)

**Comment by Gamemechanicwow** [comment]
Wasn't available until patch 1.4
