### ISSUE TITLE
Bubbly Fissures

### ISSUE THREAD

**Issue by Simp-N** [Wall-core/Everlook-Bugtracker#5]
Two issues: there are three bubbly fissures that do not give underwater breathing, and one fissure appear to be missing. 

Normally the player should get a debuff called [Air Bubbles](https://classicdb.ch/?search=air+bubbles) when near a Bubbly Fissure. I went around and tested all Bubbly Fissures I could find - 11 in Desolace, 2 in Moonglade, 1 in Silverpine, and 4 in Barrens. They all worked except three in Barrens:
56, 8 Sludge Fen
55,52 Stagnant Oasis
45,23 Forgotten Pools

There should also, I believe, be a Bubbly Fissure in Westfall, where alliance druids complete their Aquatic Form quest, however when I went to test if it gave breath, I couldn't find it. It should be located at about 18,33 in Westfall. I'll supply two images:

This is from the dev server. Notice the little box and the shiprekt.
![Sorted_WoWScrnShot_220618_001601](https://user-images.githubusercontent.com/75734743/174409385-d29f627d-9b40-4952-8a01-2db70543cf24.png)

And this is from Classic.
![](https://wow.zamimg.com/uploads/screenshots/normal/989602-trial-of-the-sea-lion.jpg)

If you look at the comments for the [quest on Wowhead](https://classic.wowhead.com/quest=272/trial-of-the-sea-lion#comments), you can see a few comments dating back to vanilla that mention the bubbly fissure. Examples:
*Grab a fresh breath and swim down to it. Follow the ravine down to a bubbly fissure. If you stand in this, you get your breath back. Right next to the fissure is the chest you need.*

*When you see the anchor swim down...don't worry when you get low on breath there is a place underwater you can get more breath.  The box is next to that place.*

**Comment by NickTyrer** [comment]
Closed Here https://github.com/vmangos/core/pull/1467
