### ISSUE TITLE
Cant summon pet

### ISSUE THREAD

**Issue by Zboutsam** [Wall-core/Everlook-Bugtracker#503]
Since the last update i can't summon my pet. If I use Call Pet, it does nothing. I can't use the pet I have on stable I try to move it to the active pet slot (which appears empty) but it doesn't move and when I try to tame a new pet it appears the message that I already have a pet.

**Comment by Wall-core** [comment]
It's because the patch has been changed to a time before your pet existing. Fixed manually ingame.
