### ISSUE TITLE
Infernal cant be summoned

### ISSUE THREAD

**Issue by Olexandr66** [Wall-core/Everlook-Bugtracker#509]
Hello,

Summon infernal doesn't work after sacrificing voidwalker. 
It says I already have a pet 
It is supposed to auto dissmiss current pet but it doesnt, so if you got sacrificed void unitframe lingering you cant even manually dismiss him and you cant use infernal at all

**Comment by Olexandr66** [comment]
It also counts for any other warlock pet: after they are dead you still can't summon infernal or use gnomish mind control cap, because game thinks you still have a pet

**Comment by Wall-core** [comment]
If it works differently on classic please provide evidence but I believe that this was an original thing in vanilla.

**Comment by Olexandr66** [comment]
https://www.youtube.com/watch?v=5TywDinAWv8  - here's some proof for vw sac/infernal combo. at 5:30 mark and 10:00 mark
https://www.youtube.com/watch?v=Lq_qJOaVHjE&list=PLAB2B86E948E104FA&index=2 - succubus gets autodismissed as drakedog starts casting infernal at 0:49
