### ISSUE TITLE
Atal'ai Deathwalker's Spirit ranged aggro

### ISSUE THREAD

**Issue by ezzekielfox** [Wall-core/Everlook-Bugtracker#51]
When you kill an Atal'ai Deathwalker and their vengeful spirit spawns, it is a separate mob and if killed from range, drops aggro if nothing is nearby on its spawn, should aggro onto the party regardless and not allow players to drop combat.

**Comment by Wall-core** [comment]
Might be patch issue, tested in patch 0 as working properly.
