### ISSUE TITLE
Skill of inpeding Doom dosnt work

### ISSUE THREAD

**Issue by AzioNik** [Wall-core/Everlook-Bugtracker#510]
Skill of inpeding Doom dosnt work on 1.2 patch in duels, why? Its usable without duel

**Comment by AzioNik** [comment]
![image](https://user-images.githubusercontent.com/112306014/199549699-eac60edb-66bf-4331-a979-974fd904b523.png)

**Comment by AzioNik** [comment]
same with 
![image](https://user-images.githubusercontent.com/112306014/199549795-703c3a40-7002-4365-80a9-d0a1089f6ad5.png)

**Comment by AzioNik** [comment]
But orb I cant use anytime

**Comment by Wall-core** [comment]
It shares CD with other speed boosts in early patches.
