### ISSUE TITLE
Crafted wand does not become soulbound when equipped.

### ISSUE THREAD

**Issue by Chitzie** [Wall-core/Everlook-Bugtracker#511]
I crafted a green quality Greater Magic Wand through Enchanting and noticed that it didn't soulbind. The message prompt warning me that equipping it will bind it to me still pops up every time, but after repairing it I could list it on the Auction House. The item tooltip also retains the "Binds when equipped" label instead of showing "Soulbound" under its name when equipped.

This could be a one-off, or there might be other items out there with the same issue.

![gmwsoul](https://user-images.githubusercontent.com/117311237/199584679-43f34b32-e604-42c1-9ae9-89eb9fb52680.jpg)

**Comment by vetu104** [comment]
Delete WDB folder, your tooltip is wrong because you've been playing on a server set at a higher patch. The items is white in quality.
