### ISSUE TITLE
Mossflayer Shadowhunters and Mossflayer Scouts run away in fear on >80% of health

### ISSUE THREAD

**Issue by CipHuK** [Wall-core/Everlook-Bugtracker#513]
By some probability (I'd say 35%) the first thing Mossflayer Shadowhunters or Mossflayer Scouts might do is "%s attempts to run away in fear!" and they actually run in fear for some time (I'd say ~8sec), without any new statuses, etc.

As I understand this is expected behavior if their health drops to ~20%, but in the case of the bug, health is 80%-100%

**Comment by CipHuK** [comment]
Seems like they start running in fear only when they are linked in a group.

**Comment by Wall-core** [comment]
This is correct behavior, they are designed to aggro nearby mobs when you initially pull them making them particularly deadly.
