### ISSUE TITLE
Dire Maul Tribute as Hunter

### ISSUE THREAD

**Issue by Wylderson** [Wall-core/Everlook-Bugtracker#515]
Just gonna list with no particular order:

- Both the king and cho can be snap taunted with distracting shot but with other abilities like aimed shot (which hits the hardest) a combo of aimed shot and multi shot can at times NOT get aggro and sometimes it does. Seems to be about 50/50
- At times you can split pull the king and cho when you pet pull the boss. I found no realiable way to replicate this. Just like the threat it just happens.  Not as common however.
- When feign death resists on either cho or king the ui won't update target of target. So your pet can be the target but the king or cho chases you. UI bug?

**Comment by Wall-core** [comment]
Client issue for the UI bug, other ones are working as intended.
