### ISSUE TITLE
Spirit of Redemption gives enemy players multiple honor kills.

### ISSUE THREAD

**Issue by Smegyy** [Wall-core/Everlook-Bugtracker#528]
Spirit of Redemption gives enemy players multiple honor kills.

When you kill a player and he has Spirt of Redemption talent, you gain multiple honor kills instead of 1.

![WoWScrnShot_110522_171452](https://user-images.githubusercontent.com/117540014/200138554-36718060-b9ea-4a2d-8f6a-2bb0793fbe1b.jpg)

**Comment by Daribon** [comment]
The entire talent is bugged to the max. It is missing spell effect and death effect etc. It needs to be rewritten.

Vmangos issue: https://github.com/vmangos/core/issues/889

**Comment by Wall-core** [comment]
I'll look into it, but as Daribon said it's got some old scripting that needs to be redone and is low priority.
