### ISSUE TITLE
[Closed PTR] Charge/Intercept going too far

### ISSUE THREAD

**Issue by HS-Disq** [Wall-core/Everlook-Bugtracker#53]
Charge and Intercept are going too far in PvP scenarios. It should, when not resisted, stun the target and you land in front of them (sometimes behind). On PTR, it ended a good 5-10 yards away from the target.

**Comment by ratkosrb** [comment]
Change this config setting:

Movement.ExtrapolateChargePosition = 0

**Comment by HS-Disq** [comment]
In the client or the server?

**Comment by ratkosrb** [comment]
On the server. My reply is for the server owners.
