### ISSUE TITLE
Wetland Croco Quest

### ISSUE THREAD

**Issue by Bornlesszero** [Wall-core/Everlook-Bugtracker#530]
Can't get the Crocolisk Quest for some reason. The NPC doesn't offer anything

**Comment by Daribon** [comment]
Needs more detail.

What level did you attempt to pick up the quest at.

**Comment by Tessablanc** [comment]
Requires the prequest "Daily Delivery" in Wetlands. See also #526

**Comment by Bornlesszero** [comment]
> Needs more detail.
> 
> What level did you attempt to pick up the quest at.

Hi Dari. Tried at 19 and 24. Daily Delivery is done and still doesn't offer.

**Comment by Bornlesszero** [comment]
> Requires the prequest "Daily Delivery" in Wetlands. See also #526

Daily Delivery is done and still doesn't offer.

**Comment by Tessablanc** [comment]
Ok, that's a bug then lol.

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1630
