### ISSUE TITLE
[Herb node spawn] Behaviour is not blizzlike

### ISSUE THREAD

**Issue by MrMoustaki** [Wall-core/Everlook-Bugtracker#532]
Very fucked up herb node spawning in Everlook PTR. I only tested it on horde side, starting zone like durotar, barrens and mulgore.

Herbs should not spawn very close from each other because of pooling. Also herbs are not respecting their spawning behaviours, meaning you can see stranglekelp spawning on cliffs, silverleafs in open ground, and earthroots near trees. Need serious reviewing imo.

No need to proof anything from classic or som since it is obviously broken.

![WoWScrnShot_110122_213913](https://user-images.githubusercontent.com/98483586/200168814-b2163235-0a9d-4271-b337-d53fef81087a.jpg)
![WoWScrnShot_110522_132240](https://user-images.githubusercontent.com/98483586/200168838-215fa607-eea3-4039-bc20-851b1593a5b3.jpg)
![WoWScrnShot_110622_124048](https://user-images.githubusercontent.com/98483586/200168857-52d72786-a65d-4e4e-a83e-08282229540d.jpg)

**Comment by Wall-core** [comment]
So, go contribute the fixes to vmangos. We're aware of incorrect spawns; we have sniffs from classic but it's massive work to implement them, and it's a community driven project.
