### ISSUE TITLE
Mage's Counterspell

### ISSUE THREAD

**Issue by Bornlesszero** [Wall-core/Everlook-Bugtracker#539]
Can't remember if it was like that on pservs but it's not off GCD and I think it should

**Comment by Alakoris** [comment]
Nope, i think mage's [Counterspell ](https://vanilla-wow-archive.fandom.com/wiki/Counterspell) doesn't share GCD with the other spells. That's not a bug, but a feature of WoW

**Comment by Tessablanc** [comment]
OP said that Counterspell isn't "off" the GCD, so maybe he means it's buggy on here and has a GCD. This is a good example of how bug reports need to be written in specific language.

**Comment by Wall-core** [comment]
Counterspell is not on GCD. delete your WDB and ensure you dont have custom patches. Works fine for me.
