### ISSUE TITLE
rogue sap proc instant poison

### ISSUE THREAD

**Issue by QWERTYQWERTYQWERTYX** [Wall-core/Everlook-Bugtracker#54]
rogue sap proc instant poison
![image](https://user-images.githubusercontent.com/46333431/185788081-12c5822b-7e49-4ce3-a798-9f644e77966f.png)

**Comment by QWERTYQWERTYQWERTYX** [comment]
https://user-images.githubusercontent.com/46333431/185788230-5eafbbae-22a2-4435-991f-337077121951.mp4

**Comment by QWERTYQWERTYQWERTYX** [comment]
![image](https://user-images.githubusercontent.com/46333431/185789282-3643f26f-e3dd-4d11-83bf-a7b8d15a3251.png)
same with any ability

**Comment by Wall-core** [comment]
Working as intended, this is an old private server mechanic reimplemented. Use mind numbing, wound or crippling on mainhand in pvp and proc it with sap or gouge.
