### ISSUE TITLE
Mage: Blizzard spell targeting reticle issues

### ISSUE THREAD

**Issue by Paxroy** [Wall-core/Everlook-Bugtracker#540]
**Issue 1: Can't activate reticle while moving**
- Trying to cast Blizzard while moving results in "You fail to cast Blizzard: Can't do that while moving". You can however stand still, cast it to activate the targeting reticle, and then move (the reticle stays active).
- In Classic you could activate the reticle while moving. [Video proof (@ 9:33)](https://youtu.be/SxMc2GoP33c?t=573).

**Issue 2: Reticle turns red before maximum range is reached**
- Replicate by moving the reticle just to where it turns red, then move it slightly more and you can still cast.

Both issues are demonstrated in [this recording](https://www.youtube.com/watch?v=D47Dzw2s98k).

**Comment by Daribon** [comment]
You were never able to cast blizzard while moving in vanilla.
It is a classic feature.

**Comment by Paxroy** [comment]
Fair enough. Classic feature is the right term, with emphasis on feature. Just doesn't make sense that you have to stand still to activate the reticle but can then move freely (compare with nades, no need to stand still to activate the reticle).

**Comment by Wall-core** [comment]
I will release a custom patch for 1.12 client to match 1.14 functionality for this, and it will be compatible with Everlook.
