### ISSUE TITLE
Ruins of Ahn'Qiraj: Ossirian the Unscarred

### ISSUE THREAD

**Issue by rope123** [Wall-core/Everlook-Bugtracker#541]
On our first pull we got Ossirian down to around 40k hp and we wiped, however,  on our second pull, the crystals that were previously clicked during first pull did not come out of the ground, only the ones that we did not manage to click during our  first wipe were available to us, the crystals however did appear later in the fight and we were able to successfully slay the boss.

**Comment by Wall-core** [comment]
they have a respawn timer
