### ISSUE TITLE
Weird WSG charge

### ISSUE THREAD

**Issue by beefstewart** [Wall-core/Everlook-Bugtracker#542]
Outside of horde base towards ramp I charged a mage. We were standing roughly above the tunnel as in the tunnel was below the ground we were standing on. Instead of charging into the enemy, I (full charging sprint) ran all the way into the horde base and around the corner and into the tunnel and down the tunnel roughly to the spot where the mage had been (above ground). 

So, it was like my character registered that the enemy was in the tunnel when I (and he) was above ground on ramp and I charged all the way around and down into tunnel where nobody was.

**Comment by Wall-core** [comment]
Has something to do with charge logic according to Brotalnia, and unfortunately this is something I won't be tinkering with personally. Report the issue to vmangos bugtracker please.
