### ISSUE TITLE
Bugged patrool guards in Theramore Isle

### ISSUE THREAD

**Issue by AzioNik** [Wall-core/Everlook-Bugtracker#543]
![image](https://user-images.githubusercontent.com/112306014/200843382-b5e35b2f-eff2-4d5d-b45b-244e24dd07d5.png)

**Comment by AzioNik** [comment]
@Wall-core

**Comment by Wall-core** [comment]
Not bugged, they just seemed to have synced up during their patrol pathing purely on luck
