### ISSUE TITLE
Mage talent Magic Attunement 

### ISSUE THREAD

**Issue by r0mivk** [Wall-core/Everlook-Bugtracker#544]
It seems like it doesn't work, after putting two talent points into it I still take same amount of magic damage from the mobs...
Tested on the water elementals in STV on the little island in the north-west part of the STV. Dampen Magic rank 3 with two talent points used, damage taken is the same with and without talent points.

**Comment by Energizer188** [comment]
Tested with the last rank of Dampen Magic, same result as you. The talent doesn't work at all

**Comment by Simp-N** [comment]
Keep in mind that Dampen Magic has been changed recently to be capped at 50% of the initial damage, which may be why you don't appear to gain any reduction beyond that. 

This is Wall's comment on Discord:
>Fix dampen magic reducing melee damage below half

This seems to be a change that came in 1.12, per the patch notes posted at the bottom [here](https://wowwiki-archive.fandom.com/wiki/Dampen_Magic).

Before 1.12 it may have been capped at 1 in vanilla, according to this [video](https://www.youtube.com/watch?v=nZjsikcDkUk).

Pservers have, for as long as I've known, had no cap on Dampen Magic.

**Comment by Wall-core** [comment]
> Keep in mind that Dampen Magic has been changed recently to be capped at 50% of the initial damage, which may be why you don't appear to gain any reduction beyond that.
> 
> This is Wall's comment on Discord:
> 
> > Fix dampen magic reducing melee damage below half
> 
> This seems to be a change that came in 1.12, per the patch notes posted at the bottom [here](https://wowwiki-archive.fandom.com/wiki/Dampen_Magic).
> 
> Before 1.12 it may have been capped at 1 in vanilla, according to this [video](https://www.youtube.com/watch?v=nZjsikcDkUk).
> 
> Pservers have, for as long as I've known, had no cap on Dampen Magic.

This is correct
