### ISSUE TITLE
5/5 improved Corruption

### ISSUE THREAD

**Issue by Xelrock** [Wall-core/Everlook-Bugtracker#548]
when specced into 5/5 improved corruption as warlock casttime goes to 2 sec, with 4/5 it worked as expected but with 5/5 it went back to 2s casttime, worte a ticked about it but got send here

**Comment by Xazamas** [comment]
I have 5/5 improved corruption and my cast time is instant.

**Comment by Godmatik** [comment]
Probably an add-on issue, do you have Zygor by chance?

**Comment by Wall-core** [comment]
Either addons, WDB or custom patch causing this. Disable addons, delete WDB folder and ensure you have no custom patches in data folder.
