### ISSUE TITLE
 [Closed PTR] UnitHealth(), UnitHealthMax() working wrong

### ISSUE THREAD

**Issue by laytya** [Wall-core/Everlook-Bugtracker#55]
UnitHealth(), UnitHealthMax() on friendly units gives percentage values not real HP... all addons show crazy numbers

**Comment by Simp-N** [comment]
In vanilla UnitHealth and UnitHealthMax return percentage values if the target's HP isn't known, so to say. However, they should return actual HP points for the player (edit: and party members). There are addons that attempt to estimate the HP for other players and NPCs.

In Classic I believe they changed these functions to give the precise HP, for whatever reason. 

Quote from [WoWwiki](https://wowwiki-archive.fandom.com/wiki/API_UnitHealth?oldid=266544), september 2006: 
> Returns the current health of the specified unit. The health is returned in real points only if the unit is in the player's group (party or raid). Otherwise, a percentage is returned (0-100). (Note, that the player, the player's pet, and any group member pets are considered to be in the group.)

**Comment by laytya** [comment]
Dont undesrstad what the point to not give real numbers of friendly player? 
just to make pain to addon authors?
