### ISSUE TITLE
Improved Drain Soul

### ISSUE THREAD

**Issue by kalleas1** [Wall-core/Everlook-Bugtracker#550]
EDIT: SOLVED

Improved Drain Soul only works when Drain Soul gets the killing blow but it is supposed to work when either the warlock or the pet gets it

**Comment by Godmatik** [comment]
I'm fairly certain it's blizzlike for it to only proc from the warlock's killing blow, not the pet

**Comment by kalleas1** [comment]
I thought the issue was that it HAD to be the drain soul getting the killing blow and not the warlock (this was an issue on classic as well) but it was just bad testing on my part. And when it comes to the pet getting the blow it was not until 2.0 so yea, my b
