### ISSUE TITLE
/target macro

### ISSUE THREAD

**Issue by SpacePoint0** [Wall-core/Everlook-Bugtracker#551]
Hi!

As you can see when I try to use the /target macro on a certain target normally it would say something like "Unknown Unit". But it just targets a random unit is this fixable or is it just normal.

(My /target macro is on my CTRL+E key at the bottom right side of the screen.)

Kind Greetings,

SpacePoint0
![WoWScrnShot_111222_150034](https://user-images.githubusercontent.com/115450700/201477633-1afa8e92-e7fe-486d-834f-4788e4a1ec1b.jpg)

**Comment by Bowny1** [comment]
you can use 

/script TargetByName("Antonio Perelli",true);

the true stands for an exact match
