### ISSUE TITLE
Event message visible on harpys in the Oracle glade (Teldrassil)

### ISSUE THREAD

**Issue by snubbenn** [Wall-core/Everlook-Bugtracker#553]
Pic related. Doesn't affect all mobs, seems random.

**Comment by snubbenn** [comment]
![fury](https://user-images.githubusercontent.com/115948562/201487860-871741f6-9efe-4589-9956-b674be269a79.png)
![sorceress](https://user-images.githubusercontent.com/115948562/201487865-aed5642a-385c-46f7-be0e-25aa1184579c.png)
![wind witch](https://user-images.githubusercontent.com/115948562/201487866-a5433afb-0534-436d-9d32-e4e19bcce445.png)

**Comment by Gamemechanicwow** [comment]
That's most likely caused by an addon.
