### ISSUE TITLE
Hunter Pet: Boar - charge not available on tame

### ISSUE THREAD

**Issue by Hygnxx** [Wall-core/Everlook-Bugtracker#555]
I just tamed a  Young Thistle Boar, and Thistle Boar and neither of them have the Charge ability. Both are supposed to have it: [https://www.wow-petopia.com/classic/abilities.php](url)

**Comment by Gamemechanicwow** [comment]
Boars can't learn charge until patch 1.9.

http://shagu.org/hunter/
