### ISSUE TITLE
Fishing Bugs

### ISSUE THREAD

**Issue by TurnerDean** [Wall-core/Everlook-Bugtracker#559]
Getting Raw Redgill, Raw Mithril Head Trout, and Lightning Eels at lvl 10 fishing in the echo isles. Seems like level thresholds need to be set for some fish.

Additionally, While channeling the fishing cast it will often end half way through the channel with "no fish are hooked" even without any interaction with the client.

**Comment by Wall-core** [comment]
Fishing tables are incorrect and need to be redone, it's massive work though. They're generally correct but some issues still.
