### ISSUE TITLE
Casting lower level of DoT refreshes DoT duration clientside.

### ISSUE THREAD

**Issue by 123iqpl123** [Wall-core/Everlook-Bugtracker#56]
I don't know how or why this is happening but both me and Keftenk noticed that if you cast lets say Moonfire (Rank 10) and then want to cast another Moonfire but don't want to refresh the dot and cast Moonfire (Rank 9), for some reason the dot refreshes on clientside, but only on your client. The person who has the DoT sees the DoT not refreshing, but the caster sees the DoT as full duration.

I tested this with Druid moonfire and Warlock Curse of Agony & Corruption and with / without addons on. Expected behaviour is that you don't see the DoT refreshing at all yet the instant damage of the spell applies. From what I understand this is purely a visual bug, but a bug nonetheless.

**Comment by Wall-core** [comment]
Client issue
