### ISSUE TITLE
RFC graveyard

### ISSUE THREAD

**Issue by Kidcudi123** [Wall-core/Everlook-Bugtracker#560]
You run from razor hill instead of outside org

**Comment by Daribon** [comment]
I believe this is because Wall applied the graveyard progression fix from here:
https://github.com/vmangos/core/pull/1637

Durotar, Northern Durotar GY was added in patch 1.6.0.
The graveyard used prior to 1.6.0 for RFC was Durotar, Razor Hill GY.
