### ISSUE TITLE
I killed a Defias pillager and it kept casting fireballs at me despite being dead

### ISSUE THREAD

**Issue by Elitegamer010** [Wall-core/Everlook-Bugtracker#563]
![WoWScrnShot_111322_161907](https://user-images.githubusercontent.com/30178237/201532733-9c592c43-dd59-4588-b875-b27932ed1395.jpg)
![WoWScrnShot_111322_161915](https://user-images.githubusercontent.com/30178237/201532739-b03714a2-6283-4b35-9bcc-fe56fdbdbeba.jpg)
![WoWScrnShot_111322_161901](https://user-images.githubusercontent.com/30178237/201532740-54d039bc-8778-4572-9b02-a21d2cbe1b43.jpg)

**Comment by Wall-core** [comment]
Close your client and delete your WDB, should fix.
