### ISSUE TITLE
Drowning after hearthed

### ISSUE THREAD

**Issue by Keftenk** [Wall-core/Everlook-Bugtracker#564]
If you hearth underwater, you can still drown in the inn until you make an action. If you stand still and don't cast or use any abilities you will drown in front of your inn keeper.

**Comment by Wall-core** [comment]
It should probably validate your coordinates with heartbeat but this is how it's basically always been so I wouldn't expect a fix any time soon. Same behavior when you respawn next to a mob that has no movement generator, it tracks enemies based on motion so if you res and don't move it wont aggro.
