### ISSUE TITLE
Incendia Agave in the "Sacred Fire" quest in thousand needles does not have increased spawns

### ISSUE THREAD

**Issue by reetarded** [Wall-core/Everlook-Bugtracker#567]
As title states, it is not a 10 sec respawn quest object. Currently not that much competition so not a big issue, but it will be in a couple days. Should respawn every 10 sec like other quest objects.

**Comment by Wall-core** [comment]
It has 10 second spawn time, it's pooled. That means it spawns at a random point in the pool every 10 seconds with a limit of X active spawns.
