### ISSUE TITLE
Gubber Blump drop your skills in fishing to 75 if u had Journeyman+

### ISSUE THREAD

**Issue by MrKoma** [Wall-core/Everlook-Bugtracker#573]
I was fishing in Darkshore and when I filled my bags I wanted to sell some things to Gubber Blump but I accidently pressed dialogue and he taught me Apprentice fishing but I already had Journeyman skill and now I'm stuck at 95/75 and I can't learn Journeyman skill again, and I can't get skills for fishing, I also can't forget fishing *pls help. Then I went to the nearest fishing trainer who is not from danassus because I learned the Journeyman skill there. And I saw that other trainer have the same problem
![WoWScrnShot_111422_200040](https://user-images.githubusercontent.com/104138408/201746799-d26a96f4-c43f-48d8-af2a-e6ccb62e195b.jpg)

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1630

**Comment by Wall-core** [comment]
File a ticket ingame and i'll fix your spells manually
