### ISSUE TITLE
Archmage Arugal in Shadowfang Keep bugged

### ISSUE THREAD

**Issue by P-l-i-n-y** [Wall-core/Everlook-Bugtracker#574]
Seems the issue is that he will teleport to a random 3rd spawn point that I haven't seen elsewhere, messing up his pathing and bugging combat. For a while no one was able to attack him as he ported around killing people, but one rogue was able to vanish which somehow cleared the bug and was able kill him. I've got a video of halfway through the encounter, if you wanna see @Wall just reach out.

**Comment by Wall-core** [comment]
Known issue, working on fixing LoS for his room
