### ISSUE TITLE
Dangerous! Tarren Mill cannot turn in even though its complete

### ISSUE THREAD

**Issue by Painsawz** [Wall-core/Everlook-Bugtracker#578]
I have fully completed the Dangerous! quest. Went to turn in but High Executor in Hillsbrad Foothills will not accept the quest to be complete. I have deleted my WDB, tried to relog and reload. Pictures will be attached showing the quest completed, as well as the quest giver who isnt allowing me to hand in. I also remember killing each of the 4 required kills within the past two days so i know it should be finished. 
![Github 1](https://user-images.githubusercontent.com/78190876/201860298-f090b25a-41c3-4564-87ec-66651e54fabe.png)
![Github 2](https://user-images.githubusercontent.com/78190876/201860382-58d2a072-1654-458e-9802-a05aa3e90b7a.png)

**Comment by Wall-core** [comment]
Close your client and delete your WDB.
