### ISSUE TITLE
Macro: Showing the wrong icon when put on actionbar.

### ISSUE THREAD

**Issue by wesen247** [Wall-core/Everlook-Bugtracker#58]
1. Was making macros.
2. Second macro I created appeared with same icon as the first when put on actionbar.
3. Relogging fixed this.
4. Restarting game made this visual bug appear again.

**However, when trying to reproduce this, third time restarting game I noticed that icons where correct again.
Also, the macro is still the right one, this only has to do with the icons.**

1.
![icons_for_macros_changing](https://user-images.githubusercontent.com/47139713/185803233-f56b612b-5a03-43c7-aa23-504f2dc5115f.png)

2.
![icons_for_macros_changing2](https://user-images.githubusercontent.com/47139713/185803235-47a40721-44a5-4a42-9ddc-320e6acf731f.png)

**Comment by Wall-core** [comment]
This is a client issue.

**Comment by wesen247** [comment]
Would you suggest we download another 1.12 client instead of Elysium, or does your answer suggest this is what it is?
