### ISSUE TITLE
Improved Ghost Wolf talent

### ISSUE THREAD

**Issue by Xantoni** [Wall-core/Everlook-Bugtracker#580]
Improved Ghost Wolf talent does not bring down cast time. 

Currently, i have one point on it and it should brind the cast time down to 1 second, but the spell cast is still 2 seconds.

**Comment by Godmatik** [comment]
Does it still happen if you have all addons disabled?  Especially Zygor addon. Also delete WDB folder with game closed

**Comment by Xantoni** [comment]
I run no addons whatsoever. Already deleted WDB and checked if i had patch-3, which is not the case.

I downloaded the Elysium project client by the way.

**Comment by Xantoni** [comment]
Wait, i'm stupid, i thought Ghost Wolf cast time was 2 seconds but in vanilla it's 3. I'm so sorry for making you waste your time.
