### ISSUE TITLE
Seargent Bly (from ZF) - Wrong dialogue 

### ISSUE THREAD

**Issue by Godmatik** [Wall-core/Everlook-Bugtracker#582]
When you talk to Seargent Bly to begin the fight with him in ZF, he repeatedly gives the wrong text, see below.

![Bly](https://user-images.githubusercontent.com/37913400/202012945-dde0e1d6-5155-4ab9-a3db-a57408fb42f0.png)

**Comment by Wall-core** [comment]
Delete your WDB and any custom patches you have.

**Comment by Godmatik** [comment]
I deleted WDB already before server launch - our entire party saw this invalid dialogue. This is not client side.
