### ISSUE TITLE
[Trinket] Uther's Strength

### ISSUE THREAD

**Issue by Godmatik** [Wall-core/Everlook-Bugtracker#583]
When using Uther's Strength trinket, you can move while casting it. Also can't cancel the cast.

https://www.wowhead.com/classic/item=11302/uthers-strength

**Comment by Wall-core** [comment]
Delete your WDB and any custom patches you have, this item is a proc-on-received-hit trinket.

**Comment by Godmatik** [comment]
I have no custom patches, and already deleted WDB before server launch
