### ISSUE TITLE
NPC #2058 Deathstalker Faerleia

### ISSUE THREAD

**Issue by CrackerzDLite0** [Wall-core/Everlook-Bugtracker#585]
NPC #2058 Deathstalker Faerleia starts the quest #452 Pyrewood Ambush.

When group arrived at NPC location, it would not offer the quest.  A GM ticket was submitted, but was not resolved before the group disbanded.  Luring a mob to kill the npc eventually fixed this problem when she respawned.

**Comment by Wall-core** [comment]
she has a long reset delay on her script.
