### ISSUE TITLE
Parts for Kravel quest gray at 39

### ISSUE THREAD

**Issue by reetarded** [Wall-core/Everlook-Bugtracker#586]
https://www.wowhead.com/classic/quest=1112/parts-for-kravel

It is supposed to go grey at 45 and give reduced xp at beginning at 42. Normally if it was off 1 or 2 I wouldn't care but this was off over 6 levels.

**Comment by Daribon** [comment]
It is the correct behavior.
The quest was changed in patch 1.9.0. The server is currently running a patch below 1.9.0

Patch 1.9.0:
`The level for the quest "Parts for Kravel" has been raised to bring it in line with the other quests of the Kravel series.`
