### ISSUE TITLE
Mind control: Enemy spells does not appear

### ISSUE THREAD

**Issue by wesen247** [Wall-core/Everlook-Bugtracker#59]
No enemy spells apear when mind controlling them. Tried disabling all addons just to make sure but produced the same result.

1.
![bild](https://user-images.githubusercontent.com/47139713/185805528-bf01d901-8f90-4c30-ba90-14c7950261ef.png)

**Comment by Wall-core** [comment]
You cannot cast enemy player spells while mind controlling them.
