### ISSUE TITLE
Nothing but copper in Westfall

### ISSUE THREAD

**Issue by Tessablanc** [Wall-core/Everlook-Bugtracker#591]
It seems the entire zone of Westfall has no mining nodes except copper, including places that usually have tin like the Jangolode MIne, the Gold Coast Quarry, the Dagger Hills, and the tunnels leading to the Deadmines. There are supposed to be random silver spawns off of the tin nodes as well. But after making multiple loops through the zone at different times of day, I've found there is nothing anywhere except copper.

Here are the tin and silver node locations from Classic, which I believe to be correct since they mirror what I've seen on every pserver:

https://www.wowhead.com/classic/object=1732/tin-vein

https://www.wowhead.com/classic/object=1733/silver-vein

**Comment by Wall-core** [comment]
> Here are the tin and silver node locations from Classic, which I believe to be correct since they mirror what I've seen on every pserver:

We have sniffs directly from classic. What you're seeing is a bunch of copper that no one took, and what you're not seeing is all the tin that they did.

**Comment by Tessablanc** [comment]
No, dude, your "sniffs" from classic are wildly wrong. There's like 8,000 copper everywhere, as one of the other bug reports has mentioned. You go to Gold Coast Quarry and there's like 13 copper nodes. It's insanely wrong. Any given one of these caves in Westfall should have a total of like 8 nodes max, and like 6 copper at most. The server is clearly spawning every single possible node at the same time, rather than correctly treating them as potential nodes and staying at a total cap for any given node type for the whole zone, which is blizzlike. I remember this clearly from 2005.

Here's what's going on: there are a number of set locations in which nodes can spawn. However, there is a cap on the total number of nodes. They don't all spawn at the same time. At any given time, in Jangolode Mine, you will find a maximum of about eight, maybe six, and they will be chosen at random from the potential spawn points that are inside the mine. What we are getting instead is that every single potential node is spawned at the same time, creating an insane amount of nodes. The same thing is happening with herbs. There's a cap on the amount of Briarthorn that's supposed to be in all of Westfall, and they appear in random places which are set as potential Briarthorn spawns. What we have instead on Everlook is every single Briarthorn being popped at the same time.

This needs to be looked at and fixed. It's nuts. I've never on any server seen such a gigantic amount of resource nodes spawned simultaneously, and it's clearly because rather than capping the total number of spawns and having them appear at these potential nodes, it's just spawning every single node simultaneously, with no kind of  total cap at all. The cap is blizzlike thing and I remember people discussing it frequently back in the day.
