### ISSUE TITLE
A-Me 01 spawned in wrong spot

### ISSUE THREAD

**Issue by Godmatik** [Wall-core/Everlook-Bugtracker#592]
Found A-Me in the gorilla cave properly and did the escort, no issues.

I come back later on and see he has respawned just south of Marshal's Refuge and not back inside the cave.
![WoWScrnShot_111622_163828](https://user-images.githubusercontent.com/37913400/202310046-e5c0af86-0757-44f7-b4c7-b85b0f6a509e.jpg)

**Comment by Wall-core** [comment]
pretty sure he died there.
