### ISSUE TITLE
Exiting Shadowform triggers a GCD

### ISSUE THREAD

**Issue by Godmatik** [Wall-core/Everlook-Bugtracker#593]
Currently: When you exit shadowform as a priest, you trigger a GCD.

How it should work: You should only trigger a GCD when entering shadowform, not exiting it.

Proof from vanilla (GCD triggered when he cast shield, then dispel, but not when he left shadowform):
https://www.youtube.com/watch?v=sALZHCmAMVo&t=1423s&ab_channel=ErikB%C3%A4cklund

**Comment by Wall-core** [comment]
Shadowform puts you on GCD; it's built into 1.12 client and is behavior within the client. And if you watch that vid, you can clearly see that happening; He dispels himself, and removes shadowform at end of gcd on dispel, which triggers another gcd. Observe his shadowform icon on bottom left.
