### ISSUE TITLE
Sputtervalve has the wrong dialogue in "the glowing shard" quest

### ISSUE THREAD

**Issue by Katyushia** [Wall-core/Everlook-Bugtracker#594]
in the glowing shard quest you need to find sputtervalve in ratchet and talk to him to find out where to hand it in right now he appears to give completely unrelated dialogue when ask about the shard.

**Comment by tulabutt** [comment]
Adding to the above here. Encountered this bug tonight. See: 

Quest dialogue for the The Glowing Shard is currently bugged. After finding and speaking to Sputtervalve, he returns the following incorrect dialogue (see below and attached): 

**You have shown me your desire, and have payed with precious stone. I will teach you...**
The above line is actually dialogue pulled from the npc Gloom'rel (see here: https://wowpedia.fandom.com/wiki/Gloom%27rel) 

The correct dialogue for Sputtervalve can be found here: https://wowpedia.fandom.com/wiki/Sputtervalve?so=search
**The Glowing Shard
Interesting, interesting... I know of a druid that lives atop the hill above the Wailing Caverns, <name>. She might be able to tell you more about this shard you have found.

Now, I must get back to work!**

![glowingshard1](https://user-images.githubusercontent.com/16416075/202352193-31c7defe-099b-48ff-b83b-dd9fdbcf7074.jpg)
![glowingshard2](https://user-images.githubusercontent.com/16416075/202352207-e98d87c8-52fb-4d1f-8965-214b66508788.jpg)

**Comment by NickTyrer** [comment]
Thanks, closed here https://github.com/vmangos/core/pull/1630
