### ISSUE TITLE
Something is wrong about ore density/respawn

### ISSUE THREAD

**Issue by tr33t** [Wall-core/Everlook-Bugtracker#596]
Something is wrong about ores. In Redridge orc cave (north) i've seen 20+ nodes at same time, u can stay mining forever, before u mine the last one, another will spawn. Shouldn't spawn that many. And other zones are too many nodes spawned. Copper is everywhere. Density is too high. Didnt see this in other servers like Nost, Lights hope or classic. Also the node respawn is fast, even more than Som (wich had increased respawn)

**Comment by Wall-core** [comment]
Spawns were cranked up for the first two weeks because we have over 10k active players going through zones. They'll be turned down over the coming weeks, but this is a temporary solution to deal with the mega rush.
