### ISSUE TITLE
Hair Clipping through Southsea Head Bucket

### ISSUE THREAD

**Issue by GomOnHyjal** [Wall-core/Everlook-Bugtracker#597]
![image](https://user-images.githubusercontent.com/77355746/202380884-4d376571-f1ac-4533-b8ce-93d6751f8f6a.png)

Unsure why this is happening, but this particular item seems to not understand hair.

https://classicdb.ch/?item=20640

**Comment by Wall-core** [comment]
That is entirely client-side, cannot be fixed.
