### ISSUE TITLE
[Spell] Mind Vision doesn't work properly

### ISSUE THREAD

**Issue by Godmatik** [Wall-core/Everlook-Bugtracker#599]
Priest spell "Mind Vision" should have a near unlimited amount of range, but after 100-200ish yards or so if you attempt to jump to another farther NPC, the point of view goes back to the priest, so the range is very limited as a result.

Yes I am using rank 2.

**Comment by Wall-core** [comment]
It's likely due to grid optimization. Sorry, but either you get a huge no-layer server with allocated grid usage or infinite mindvision range and more lag.
