### ISSUE TITLE
NPC pets not responding to threat

### ISSUE THREAD

**Issue by Simp-N** [Wall-core/Everlook-Bugtracker#6]
Pets of NPCs will not change aggro from their initial target. No matter how much damage you cannot pull aggro from the first taget the pet had. The only way to grab aggro is with Warrior's Taunt. I have tested this with four pets: 
[Razormane Wolf](https://classicdb.ch/?npc=3939) (which is a pet of Razormane Hunter)
[Skullsplitter Panther](https://classicdb.ch/?npc=756) (Skullsplitter Hunter)
[Scarlet Hound](https://classicdb.ch/?npc=10979) (Scarlet Hunter)
[Voidwalker Minion](https://classicdb.ch/?npc=8996) (Burning Blade Apprentice)
It may be a general issue for all NPC pets.

**How to reproduce:**
1. Be a hunter. Body pull the NPC pet and do not deal any damage to it. 
2. Have your pet attack the other pet.
3. Notice that no matter how much damage is done, it will not change aggro.

[Here's a video example.](https://streamable.com/uby9i2) Notice also that the pet does not even attack the other target even when I feign death, but rather goes out of combat. 

I have also tested this with two players, rather than hunter + pet, and it's the same issue.

**Comment by Twigie** [comment]
This was fixed here:
https://github.com/vmangos/core/commit/bbc80766d6d28570ce9e0ccc7a3d89d830c03a89
