### ISSUE TITLE
Double Rashona

### ISSUE THREAD

**Issue by Simp-N** [Wall-core/Everlook-Bugtracker#600]
Currently there are two spawns of the Orgrimmar Cloth turn-in NPC, [Rashona Straglash](https://classicdb.ch/?npc=14726). One spawned in the tailor hut in The Drag, and one spawned in the leatherworker hut next-doors. According to a comment on [Wowhead](https://www.wowhead.com/classic/npc=14726/rashona-straglash), she may initially have been in the leatherworking hut, and then moved to the tailor hut in a later patch, but now it appears she's up in both places on the server.

*edit * Looking on the vmangos database it looks like she's supposed to be in the leatherworker hut in 1.5, and then moved to tailor in 1.6. I'm guessing the double spawn is an oversight from having cloth turn in available from the start.
![rs1](https://user-images.githubusercontent.com/75734743/202483951-753c2e92-fc0d-43ef-a977-cb0f8b99f2ca.png)
![rs2](https://user-images.githubusercontent.com/75734743/202484234-55f89e3b-0419-41b9-a5f9-fbefe13fcc43.png)

**Comment by Daribon** [comment]
I see the issue. Incorrect minimum patch set for the NPC.
I will fix it soonish.
