### ISSUE TITLE
Janice Felstone - Missing RP

### ISSUE THREAD

**Issue by Godmatik** [Wall-core/Everlook-Bugtracker#605]
NPC Janice Felstone should periodically scream for help, but currently does not - this is one of the only NPCs that was actually given a voice line associated with them in Vanilla.

**Source:**

Janice Felstone was a human ghost located at the Felstone Field farm in the contested territory of the Western Plaguelands. She would occasionally scream out for help.

https://wow.gamepedia.com/Janice_Felstone

You can also see the described behavior from Joana's speedrun from patch 1.10: https://youtu.be/jKPDoC8EraY?t=307

**Comment by NickTyrer** [comment]
I dont see anything at the timestamp in the video.

**Comment by Godmatik** [comment]
> I dont see anything at the timestamp in the video.

@NickTyrer Listen at the audio 5:08

You can clearly hear in the background "Help me!"
Her other voiceline she says "I need help!"

**Comment by NickTyrer** [comment]
Ah, I thought you meant it was RP text yell.

**Comment by NickTyrer** [comment]
Thanks, closed here https://github.com/vmangos/core/pull/1630

**Comment by NickTyrer** [comment]
As an added bonus I have added her missing gossip for when you complete her quest chain as well.

**Comment by Godmatik** [comment]
Nice!
