### ISSUE TITLE
respeccing gives both ranks 1 and final ranks available for use on Warrior

### ISSUE THREAD

**Issue by Pluuf** [Wall-core/Everlook-Bugtracker#61]
When respeccing from fury into fury I got both ranks of Bloodthirst available, while I only should have the highest rank as a warrior
![image](https://user-images.githubusercontent.com/66675502/185941846-ccb6c5a2-6f88-43ad-85da-b7b92fe5f7b8.png)

**Comment by HS-Disq** [comment]
That's an UI bug coming from Vanilla for the warrior class where only the highest available rank is available. Relogging will fix that.

Not a bug.

**Comment by Pluuf** [comment]
Aight, thanks!
