### ISSUE TITLE
Wrong graveyards

### ISSUE THREAD

**Issue by Babangida18** [Wall-core/Everlook-Bugtracker#611]
Hello. First of all, when u die at Raven Hill, ur spirit appears at Darkshire instead of Westfall GY. Also if u die in Shimmering Flats, ur spirit appears at Barren`s lift, instead of Tanaris GY.

**Comment by Daribon** [comment]
Raven Hill Graveyard wasn't added until patch 1.8.0, server is not set to 1.8.0 yet.
Prior to 1.8.0 if you died at Raven Hill you would get sent to Darkshire. The behavior correct.

1.8.0 patch notes:
`A Graveyard has been added to Duskwood at Raven Hill Cemetery.`

In regards to Shimmering Flats, read my comment here:
https://github.com/Wall-core/Everlook-Bugtracker/issues/524#issuecomment-1320219466
