### ISSUE TITLE
Pattern: Frostsaber Leggings

### ISSUE THREAD

**Issue by Godmatik** [Wall-core/Everlook-Bugtracker#617]
This pattern is way too common of a drop from the Winterfall Den Watchers, I already have 6 in my bag and have only been killing them for less than an hour.

Per wowhead, the drop rate should be ~3%

https://www.wowhead.com/classic/item=15747/pattern-frostsaber-leggings

**Comment by NickTyrer** [comment]
it's set to 3.8 in the vmangos db, maybe you just got lucky.
