### ISSUE TITLE
Centipaar Swarmer's Swarms will sometimes have 2k+ hp

### ISSUE THREAD

**Issue by GomOnHyjal** [Wall-core/Everlook-Bugtracker#618]
![image](https://user-images.githubusercontent.com/77355746/202812340-e9098d31-f718-4303-b257-395690b30ac7.png)

The adds that spawn off of these mobs will periodically bug out and spawn with far too much hp. The expected hp value of these adds is supposed to be 1.

https://classicdb.ch/?npc=5457

**Comment by Wall-core** [comment]
Seems like an addon issue or if you're using 1.14. Silithid swarm is lvl 21-22 mob. Delete your WDB perhaps.

**Comment by GomOnHyjal** [comment]
No, these are the mobs that spawn from the Tanaris Centipaar area. I can confidently state that this is not simply an addon issue, they will need to be tanked from my voidwalker and dotted separately as if they're an entirely new mob. 

For clarification, the mob pictured is the add that the Centipaar Swarmer will spawn. 90% of the time, it spawns at 1 hp.
