### ISSUE TITLE
Eyes of the beast

### ISSUE THREAD

**Issue by codycigar69** [Wall-core/Everlook-Bugtracker#619]
the hunter spell Eyes of the beast is pretty buggy, can't be rechannelled from a short distance and makes your pet/character get stuck in place until you recast it. Also causes random disconnects.

**Comment by Godmatik** [comment]
Mind Vision spell has similar issues, you can't go very long distance with it, even though it should have near unlimited range. It just cancels and focuses back on your character channeling.

**Comment by Wall-core** [comment]
> Mind Vision spell has similar issues, you can't go very long distance with it, even though it should have near unlimited range. It just cancels and focuses back on your character channeling.

Not a bug, level 1 mind vision has limited range. Same with Eyes of the Beast.

**Comment by frogguyman** [comment]
No, this is wrong. Eye of the beast only has one rank and it is unlimited range.
