### ISSUE TITLE
Shaman Elemental Focus not working right

### ISSUE THREAD

**Issue by jrdnrholt** [Wall-core/Everlook-Bugtracker#621]
Howdy,

41 Shaman.  I noticed when I open lightning bolt, lightning bolt in quick succession, if the first cast procs clearcasting then when the second bolt is cast it still uses mana and removes the clearcast.  I've noticed it happening regularly.  It' seems to work fine w/ shocks.  Thanks.

**Comment by Wall-core** [comment]
the one after that has mana cost removed
