### ISSUE TITLE
cross faction talk

### ISSUE THREAD

**Issue by chudmeister** [Wall-core/Everlook-Bugtracker#625]
nice server, fix the fact that i can see anything horde types if they pick orchish as language. noone cares about chinese padded numbers.

**Comment by Wall-core** [comment]
> nice server, fix the fact that i can see anything horde types if they pick orchish as language. noone cares about chinese padded numbers.

I've never seen this issue, likely it's an addon or client error. Post your ingame name tho, big guy.

**Comment by chudmeister** [comment]
> > nice server, fix the fact that i can see anything horde types if they pick orchish as language. noone cares about chinese padded numbers.
> 
> I've never seen this issue, likely it's an addon or client error. Post your ingame name tho, big guy.

wow tough guy anyone critisizes your server thats 40% russian and chinese and your ego cant ignore it huh? what you wanna 1v1 me in rust? just start showing players by country big guy when you gloat about a few thousand players as good numbers lol.

**Comment by chudmeister** [comment]
you can always fall back to wallcraft tho right? that was a success

**Comment by Godmatik** [comment]
You made up a random bug that doesn't exist just to try and trash him, lol, very sad
