### ISSUE TITLE
Gnomeregan Last Boss adds "Walking Bomb" do no damage

### ISSUE THREAD

**Issue by Tixlenra** [Wall-core/Everlook-Bugtracker#626]
Gnomeregan Last Boss (https://www.wowhead.com/classic/npc=7800/mekgineer-thermaplugg) adds "Walking Bomb" do no damage
https://www.wowhead.com/classic/npc=7915/walking-bomb

**Comment by Wall-core** [comment]
They do damage; it's just not marked in combat log. Watch your HP.
