### ISSUE TITLE
Quest Ammo for Rumbleshot - (Missing event)

### ISSUE THREAD

**Issue by Aurigon** [Wall-core/Everlook-Bugtracker#629]
The completion of this quest should trigger a mini-event with the dwarves by the campfire performing a shooting exercise, with various sounds and emotes. At the present state, once the quest item is turned in nothing at all happens.

Here is a video of the event fully scripted: https://www.youtube.com/watch?v=wCe_9PlTKsw

**Comment by Wall-core** [comment]
It's disabled due to issues with the object spawns creating lag.
