### ISSUE TITLE
Graveyard Location Thousand Needles

### ISSUE THREAD

**Issue by Kidcudi123** [Wall-core/Everlook-Bugtracker#632]
Dying at Shimmering flats as Undead takes you to The Great Lift and not the closest graveyard

**Comment by Kidcudi123** [comment]
This corpse run makes shimmering flats pvp unplayable im beyond tilted (GAMEBREAKING)

**Comment by Wall-core** [comment]
> This corpse run makes shimmering flats pvp unplayable im beyond tilted (GAMEBREAKING)

Take a deep breath and you'll be alright. I'll revert it, but just know that it's original vanilla graveyard you're crying about; and the tears you shed here are the same ones shed in patch 1.4 when blizzard decided to give ally the eastern graveyard access. Authentic Vanilla experience for you :)

**Comment by Kidcudi123** [comment]
Danke Schön! :P

**Comment by Daribon** [comment]
It is impossible that you died in Shimmering Flats and didn't get sent to Shimmering Flats GY if wall applied the fix from earlier today.

You either lied in your github issue or wall didn't apply the fix or this happened before the fix was applied.

**Comment by Kidcudi123** [comment]
It was a discussion both in party and in general, only one guy got to the closest gy the one time he died but us other 2 died multiple times and always got to the Great Lift

**Comment by Daribon** [comment]
When did this happen and did you die in actual Shimmering Flats or just close to it.

**Comment by Kidcudi123** [comment]
I died close to the quest hub and my party mate died even way east of that, this was exactly when I posted this report

**Comment by Daribon** [comment]
The orc camp? That's not shimmering flats.

**Comment by Kidcudi123** [comment]
Shimmering Flats is where you circle around for years for the quests is what I'm refering to east / quest hub

**Comment by Daribon** [comment]
Are you talking about the gnome/goblin camp in the middle?

**Comment by Kidcudi123** [comment]
Yeah

**Comment by Daribon** [comment]
Aight, I will double check. Might be different area name.

**Comment by Daribon** [comment]
I see the issue, area changes to Mirage Raceway in the middle.

**Comment by Kidcudi123** [comment]
I can go further into detail by saying one member got to spawn at the closest graveyard when he died at the Vulture spawns at the bone thingy to the east - but another member died relatively close to where he died later and didn't spawn at the closest gy.

**Comment by Kidcudi123** [comment]
> I see the issue, area changes to Mirage Raceway in the middle.

Ok nice!

**Comment by Daribon** [comment]
It has been resolved, all areas within Shimmering Flats will send you to Shimmering Flats GY after Wall applies the fix.
