### ISSUE TITLE
Mind control breaks too early when going out of range.

### ISSUE THREAD

**Issue by yaboydarrell** [Wall-core/Everlook-Bugtracker#636]
Mind control breaks instantly upon exiting max range.   Was fixed on Elysium.
https://gfycat.com/skinnypolishedadeliepenguin

Original report copied from Elysium bugtracker.
https://github.com/elysium-project/classic-bug-tracker/issues/443
___________________________________

Unlike other channeled spells, Mind Control breaks instantly when the mind controlled target is brought out of range. This is not Blizzlike. This video for instance shows multiple instances of the target being brought outside of mind control range, and it persisting for up to five seconds (exact leeway time seems to vary, and probably resets when going back in range, though this is hard to tell from the video).

Warning: For your own sake, you may want to mute this video.
https://www.youtube.com/watch?v=PnnWDPgk_3Y

You can see him going well out of the 20 yard range (he is holy, so he does not have increased shadow range) in many of the clips. Most notably is the one at 3 minutes, where he runs very far off with the mob before the mind control breaks. Measuring this distance in-game shows he was able to run the mob almost 50 yards away from the priest's location before the spell broke. In this example, his NPC is out of range for a full five seconds.

New source - original upload [June 2005](https://web.archive.org/web/20051025114522/www.warcraftmovies.com/movieview.php?id=2740):
https://www.youtube.com/watch?v=cQ3gkWbnNnM (see 2:46 for the best example of this behaviour)

Best as I can tell from this video and others (I can provide a few more sources if you want them), is that the intended behaviour is for there to be a random leeway between 2-5 seconds that starts once you step out of range.

EDIT: After reviewing [this 3rd video](https://www.youtube.com/watch?v=WN-xySlgzQI) at 2:25, I believe the above to be slightly incorrect. The mind control appears to last the full duration here, even though the target is clearly out of range as you can tell from the Mind Control button on his action bar once the spell breaks. It appears that Mind Control should simply have a much higher chance to break once you step out of range (though it appears to always last at least 2 seconds after going out of range), scaling with how far out of range you go. Not only that, but it appears "out of range" doesn't mean outside of the normal 20 yards. All spells have some leeway, in which you can still finish casting the spell even if the target goes out of range, by at most approximately 20% of the original max range. I believe this "bonus" range is what's considered out of range for the extra chance to break to start counting down.

Repro (Nighthaven 1.5):

Mind Control any NPC or player at the edge of your Mind Control range.
Step slightly outside your Mind Control range. Note that the channel is cancelled instantly.

**Comment by Wall-core** [comment]
You're forgetting that there are talents to increase shadow range, which is what you're probably seeing.

**Comment by yaboydarrell** [comment]
I have those talents.   Regardless this report is valid & was fixed on Elysium.

**Comment by yaboydarrell** [comment]
See the videos linked from 2005.   You can clearly run the mobs outside the 20-24 yard range.   Here - and on Elysium before it was fixed - the mob will immediately drop at max range.   This does not appear to be Blizzlike behavior.
