### ISSUE TITLE
Target kept running after gouge

### ISSUE THREAD

**Issue by P-l-i-n-y** [Wall-core/Everlook-Bugtracker#64]
Going to have to work to try and recreate this one, will update or submit a new one if I pinpoint the cause but noticed during double rogue duels someone was running they had gouge applied to them and then continued to run while gouge was up. Assume they were unable to control their character through the incapacitate but will take more testing to be sure.

**Comment by Wall-core** [comment]
Likely fighting a GM or someone who got refreshed. I've only ever seen it happen then.
