### ISSUE TITLE
[Closed PTR] Rogues poison proccs

### ISSUE THREAD

**Issue by KarteLLLL** [Wall-core/Everlook-Bugtracker#65]
Tried using both crippling  poisons on two swords for hemo and two daggers for imp sprint spec(Clearly not case of the weapon speed) and still i didnt get almost any crippling poison proccs for 2 days. Im not sure is it just like that on the 1.12 version on pservers because on Classic vanilla it procced almost every second auto attack and spell.

**Comment by Wall-core** [comment]
I've seen crippling proc plenty fine, and the fact that you got some amount of procs leads me to believe it's just bad luck.
