### ISSUE TITLE
Seeing mobs that i shouldnt see (Seeing mobs that are far away)

### ISSUE THREAD

**Issue by Fearyii** [Wall-core/Everlook-Bugtracker#70]
When i am in Northshire valley i can see every mob from the kobolds in the mine to the bandits with the grapes dont think this is intended
![Screenshot_1](https://user-images.githubusercontent.com/111935564/186292700-27d074fa-0f53-40a7-9ce4-03a5c4df8d80.png)

**Comment by Wall-core** [comment]
The view distance is turned up right now, we're testing the maximum we can feasibly do while stable.
