### ISSUE TITLE
got ported to outside in BRD around boss :Bael'Gar

### ISSUE THREAD

**Issue by WE1ZARD** [Wall-core/Everlook-Bugtracker#73]

**Comment by WE1ZARD** [comment]
right corner around

**Comment by Wall-core** [comment]
What does this even mean? Were you fighting Bael'Gar and got teleported outside randomly? Did anyone else experience this? Needs more info.

**Comment by WE1ZARD** [comment]
we are just abt to pull Bael'Gar and i was runing to boss from topright corner(like T area, the topright tip spot) then suddenly got a DC, after relogin i appear at BRD ported position.
