### ISSUE TITLE
Wind Serpents as Pets, dont have Lightning Breath ability.

### ISSUE THREAD

**Issue by Totilla** [Wall-core/Everlook-Bugtracker#738]
I have Aly Hunter and have tamed more than 10 Wind Serpents from 18-30lv and none of them have Lightning Breath ability as any rank. When i check all of them with Beast Lore it says they have and after taming NONE have it. Is it only me or is BUG!

**Comment by Godmatik** [comment]
Not a bug - that pet ability does not come until patch 1.9

**Comment by Totilla** [comment]
Thank you very much!
