### ISSUE TITLE
Polymorph missing texture

### ISSUE THREAD

**Issue by r0ssi** [Wall-core/Everlook-Bugtracker#77]
When you’re polymorphed your texture is missing. There is a little box instead of you

**Comment by r0ssi** [comment]
![](https://media.discordapp.net/attachments/977210360144752680/1012072579890159626/pepehmm.png)

**Comment by Wall-core** [comment]
That's because you're casting an unknown spell; The server is currently on patch 1.2 and you obtained a later patch polymorph spell. The spell is working fine.
