### ISSUE TITLE
Weird bug after using Eyes of the Beast on 1.14 Client

### ISSUE THREAD

**Issue by Iagrah99** [Wall-core/Everlook-Bugtracker#788]
Basically, I get a weird bug after Eyes of the Beast ends. My character will become locked in place. I cannot move, or use most of my abilities. I cannot summon or dismiss my pet, because the game seems to think that I either have my pet, or that I don't. 

I can't open a ticket to ask a GM for in-game assistance because the help window never loads. The Icon is there, so I don't need the script that is on the website. It's just that when I click on it - I get an infinite loading screen.

**Comment by Deprot80** [comment]
Bro 1.14 is not supported you won't get any assistance, you use it at your own risk

**Comment by Iagrah99** [comment]
> Bro 1.14 is not supported you won't get any assistance, you use it at your own risk

Found out after I posted this. I do still get issues using 1.12, I'll remake the issue.
