### ISSUE TITLE
Quest In Dreams 

### ISSUE THREAD

**Issue by Lmao-crim** [Wall-core/Everlook-Bugtracker#79]
After spending over an Hr here and Multiple fails. Its safe to say that Either the Quest its self is messed up or When you get To far away you fail.  From what i understand from the quest you Can solo it. By either running around the tower or you can die and it will go on as normal.    So what I tried was Dyeing  with Taelan and he will loose and die aswell.  ( leading to a fail)..    Letting him die first then Running around the tower on mount ( leading to a fail)

**Comment by Lmao-crim** [comment]
![WoWScrnShot_082422_141050-min](https://user-images.githubusercontent.com/112026034/186529686-6dd908e9-6242-4f5a-ab90-94cdd481545f.jpg)
![WoWScrnShot_082422_134406-min](https://user-images.githubusercontent.com/112026034/186529690-63d67838-1bc4-4952-9115-5bc265cc93fe.jpg)

**Comment by Lmao-crim** [comment]
https://github.com/vmangos/core/issues/1348

**Comment by ratkosrb** [comment]
You must not run and you must not die. This quest is supposed to be done with a group.
