### ISSUE TITLE
Ironspine Rare bugged in SM GY

### ISSUE THREAD

**Issue by Fearyii** [Wall-core/Everlook-Bugtracker#80]
Ironspine is invisible in SM GY and you cant target him or do anything to him
![Screenshot_1](https://user-images.githubusercontent.com/111935564/186527099-cba97098-fb89-4432-9e65-0b9242e4c447.png)

**Comment by Wall-core** [comment]
He's there, his spawn location is different in patch 1.2
![image](https://user-images.githubusercontent.com/90075138/186612387-450d9034-d95e-43d3-bdfd-6080010d699d.png)
