### ISSUE TITLE
Thermaplugg bombs never explode

### ISSUE THREAD

**Issue by moyashiparty** [Wall-core/Everlook-Bugtracker#84]
![Screenshot at 2022-08-25 18-34-54](https://user-images.githubusercontent.com/1555201/186619085-f46fd71d-1fb9-46da-bf0b-0439b7092d4a.png)

They spawn correctly, but just keep stacking up forever instead of eventually exploding.

**Comment by ratkosrb** [comment]
Can't reproduce on vmangos. They explode as expected.

**Comment by Wall-core** [comment]
It explodes but no damage is dealt

**Comment by Wall-core** [comment]
Nevermind, damage is dealt - the spell just hides everything client side. I'll enable it as enhancement for Everlook

**Comment by Wall-core** [comment]
Blocked client side, cannot fix.
