### ISSUE TITLE
Iron Deposits incorrectly appearing as orange difficulty despite having 300 mining

### ISSUE THREAD

**Issue by GomOnHyjal** [Wall-core/Everlook-Bugtracker#87]
Seems like a graphical error, as the user is not presented with any failures in actually mining the iron.

![image](https://user-images.githubusercontent.com/77355746/186808135-ae2b737b-f18c-46ac-9330-2c65718e074b.png)

**Comment by Wall-core** [comment]
Client issue, delete WDB
