### ISSUE TITLE
Black Qiraji Resonating Crystal Bug

### ISSUE THREAD

**Issue by Tamaie** [Wall-core/Everlook-Bugtracker#9]
I tested on wallcraft if the majority of mounts work properly and with the Black Qiraji Battle Tank you can't dismount while moving, you have to stop to be able to dismount, and that is not how its supposed to work. I tested a lot of mounts and this one is the only one with this problem that I could find.

**Comment by Wall-core** [comment]
This is how the mount works in classic; I may change in the future but for now i'm leaving as-is

**Comment by hgarner17** [comment]
"you have to stop to be able to dismount" every other mount you can be in full sprint, jumping, falling off cliff, and still dismount no problem.  If truly unable to dismount while in motion that would certainly be a bug.

**Comment by Wall-core** [comment]
Yes that's how battle tank works in classic. You can dismount while moving by canceling the aura (or using an addon such as lazypig) but the mount spell for this specific one is unique and has this issue. I can correct but there's no real need.
