### ISSUE TITLE
Ret issues 

### ISSUE THREAD

**Issue by r0ssi** [Wall-core/Everlook-Bugtracker#90]
1. Flame of Shahram damage shown as pet damage
2. Retribution aura deals holy damage but shown as physical damage

**Comment by r0ssi** [comment]
I’ll just add problems to this ticket 
Slowing curse of Shahram doesn’t dispel by Blessing of Freedom
Warriors don’t have charge animation. Sometime they may charge from different place

**Comment by Wall-core** [comment]
All issues posted in this ticket are blizzlike and not bugs.
