### ISSUE TITLE
Hunters spell 'Flare' does not expose NPC's with stealth 

### ISSUE THREAD

**Issue by DjBootyBay** [Wall-core/Everlook-Bugtracker#93]
As the title suggest, the spell Flare does not expose NPC's with stealth abilities like the stealthed cats in north Winterspring or the panthers in STV.

**Comment by DjBootyBay** [comment]
Update: STV panthers get exposed by flare (however they don't reuse stealth after flare has faded) but the Winterspring cats don't get destealthed with flare on top of them.

**Comment by DjBootyBay** [comment]
The bugged mob in question is called 'Frostsaber Stalker'.

**Comment by Simp-N** [comment]
Can confirm, as far as the winterspring cats go. They get the Flare-debuff, but they never actually lose stealth and you cannot see them unless you go up close.

Demonstration: https://streamable.com/27za39

**Comment by DjBootyBay** [comment]
Found another mob with stealth, Syndicate Assassins in Hillsbrad Foothills, that also get destealthed by Flare as intended. This problem seems specific to the Frostsaber Stalkers.

**Comment by Simp-N** [comment]
**Ok I've checked a lot of stealthed units and there are a few that are not de-stealthed by Flare:**
[Frostsaber Stalker](https://classicdb.ch/?npc=7432)
[Jaguero Stalker](https://classicdb.ch/?npc=2522)
[Witchwing Ambusher](https://classicdb.ch/?npc=3279)
[Deviate Stalker](https://classicdb.ch/?npc=3634)
[Crag Stalker](https://classicdb.ch/?npc=4126)
[Wastewander Rogue](https://classicdb.ch/?npc=5615)
[Hive'Ashi Sandstalker](https://classicdb.ch/?npc=11723)
[Shadowclaw](https://classicdb.ch/?npc=2175)
[Fallenroot Rogue](https://classicdb.ch/?npc=4789)
[Onin MacHammar](https://classicdb.ch/?npc=6886)

**I've also checked these NPCs and they get de-stealthed like they should:**
[Shadow Panther](https://classicdb.ch/?npc=768)
[Theramore Infiltrator](https://classicdb.ch/?npc=4834)
[Shadowmaw Panther](https://classicdb.ch/?npc=684)
[Elder Shadowmaw Panther](https://classicdb.ch/?npc=1713)
[Razormane Stalker](https://classicdb.ch/?npc=3457)
[Kurzen Commando](https://classicdb.ch/?npc=938)
[Defias Night Runner](https://classicdb.ch/?npc=215)
[Shadowhide Assassin](https://classicdb.ch/?npc=579)
[Mountain Lion](https://classicdb.ch/?npc=2406)
[Syndicate Spy](https://classicdb.ch/?npc=2242)
[Syndicate Highwayman](https://classicdb.ch/?npc=2586)
[Syndicate Prowler](https://classicdb.ch/?npc=2588)
[Deviate Creeper](https://classicdb.ch/?npc=3632)
[Mad Magglish](https://classicdb.ch/?npc=3655)
[Silverman Stalker](https://classicdb.ch/?npc=2926)
[Ridge Stalker](https://classicdb.ch/?npc=2731)
[Stonevault Cave Lurker](https://classicdb.ch/?npc=4850)
[Fen Creeper](https://classicdb.ch/?npc=1040)
[Hive'Regal Ambusher](https://classicdb.ch/?npc=11730)

**Comment by Wall-core** [comment]
Those mobs that aren't unstealthing have a different stealth spell from those which are, and theirs is an aura that is applied upon spawn which isn't natively flagged as a stealth spell, thus it's not dispelled by flare. Can you verify if it's this way in classic?

**Comment by DjBootyBay** [comment]
Just checked on Classic and Frostsaber Stalkers (Winterspring cats) get destealthed by flare.
![WoWScrnShot_090122_115309](https://user-images.githubusercontent.com/112322690/187886732-d0147f49-db09-41bf-9be2-20f9f4619299.jpg)
