### ISSUE TITLE
Hunter pets unable to path properly into objects like houses

### ISSUE THREAD

**Issue by DjBootyBay** [Wall-core/Everlook-Bugtracker#95]
As displayed in the screenshot, my pet is on 'aggressive' and should run into the small house and kill the mob, but it just has the mob targeted and stands still in place as it is unable to path into the building.
![3333](https://user-images.githubusercontent.com/112322690/187072583-54f0b0d2-ae6f-4e12-b7dc-58a52c21de53.jpg)
.

**Comment by vertria** [comment]
pet patching is very weird yea

**Comment by vertria** [comment]
actually its not only pets.npcs in house cant get out.some other npc acting bad in other objects 2.

**Comment by vertria** [comment]
seen some problems in LBRS mobs cant pass rocks in orc tents area.and last boss cant move down from his hill.
