### ISSUE TITLE
Rhok'delar quest chain

### ISSUE THREAD

**Issue by Tamaie** [Wall-core/Everlook-Bugtracker#98]
Artorius the Amiable, the demon from winterspring needed for Rhok'delar quest chain, doesn't have the option transform into a demon after talking to him even tho I already have the quest to be able to make him transform.
![adas](https://user-images.githubusercontent.com/108140864/187175208-154d9d2e-b59e-4662-af2b-ec65bb47c41f.png)

**Comment by ratkosrb** [comment]
Can't reproduce it on clean vmangos, maybe @Wall-core made a mistake while porting updates.

![WoWScrnShot_083122_073030](https://user-images.githubusercontent.com/35845488/187595448-50f145ff-b404-428c-b774-18058fb000d1.jpg)
